### ISSUE TITLE
[bug][docs]

### ISSUE THREAD

**Issue by Heroes84** [apollographql/apollo-android#1021]
Hi ! I ant use apollo for android 1.0.0-alpha version but when I build project i have problem:
```
:data:nodeSetup UP-TO-DATE
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
:data:installApolloCodegen
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/build/apollo-codegen/node_modules/apollo-codegen/src/cli.js:186:16)
    at Object.runCommand (/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/build/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/build/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/build/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/build/apollo-codegen/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
:data:generateDebugApolloIR FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':data:generateDebugApolloIR'.
> Process 'command '/Users/rwawrzyniak/Documents/workspace/kotlin/com.example/data/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
35 actionable tasks: 32 executed, 3 up-to-date
```
Of course I have src/data/grapql/com.example/schema.json schema json downloaded used apollo-cli.
Fisrtly can everyone can me tell how configure apollo plugin to not use apollo-codegen only apollo-cli (I have node8 lts and apollo-cli installed globally), second why project cannot build ? Also I tried add simple query with .grapql extension and too desn't work.

**Comment by Heroes84** [comment]
I forgot mention that I want use apollo in kotlin android library, my gradle for this library:

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-platform-android'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.apollographql.android'

apply from: '../config/gradle/ktlint.gradle'
apply from: '../config/gradle/detekt.gradle'

android {
    compileSdkVersion target_sdk_version

    defaultConfig {
        minSdkVersion min_sdk_version
        targetSdkVersion target_sdk_version
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            // nop
        }
        alpha {
            // nop
        }
        beta {
            // nop
        }
        release {
            // nop
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin/'
        test.java.srcDirs += 'src/test/kotlin'
        androidTest.java.srcDirs += 'src/androidTest/kotlin'
    }

    publishNonDefault true
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    implementation project(path: ':domain')

    // Dagger
    implementation deps.dagger.runtime
    kapt deps.dagger.compiler

    // Rx
    implementation deps.rx.rxjava
    implementation deps.rx.rxandroid

    implementation "com.apollographql.apollo:apollo-runtime:$apollo_client"

    // Code analysis
    ktlint "com.github.shyiko:ktlint:0.25.1"
}
```
Where $apollo_client is 1.0.0-alpha

**Comment by sav007** [comment]
Do you have any `*.graphql` files defined ? As @martijnwalraven mentioned offline it could be the issue that we pass empty list of `*.graphql` files to code gen.

**Comment by Heroes84** [comment]
@sav007 thank for you replay. I try downloaded schema.json not using apollo-cli https://github.com/apollographql/apollo-cli but manually created introspection query from https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js, add seems to be working correctly now.
