### ISSUE TITLE
java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by tjouin** [apollographql/apollo-android#1047]
I'am running the lastest version (1.0.0-alpha2) and look like a got the same error as #1022.

`org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /Users/*/*/app/build/generated/source/apollo/generatedIR/debug/src (Is a directory)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /Users/*/*/app/build/generated/source/apollo/generatedIR/debug/src (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:52)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:90)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:90)
	at com.apollographql.apollo.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:16)
	at com.apollographql.apollo.compiler.GraphQLCompiler$write.call(Unknown Source)
	at com.apollographql.apollo.gradle.ApolloClassGenerationTask$1.execute(ApolloClassGenerationTask.groovy:53)
	at com.apollographql.apollo.gradle.ApolloClassGenerationTask$1.execute(ApolloClassGenerationTask.groovy)
	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:49)
	at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:40)
	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.outOfDate(ChangesOnlyIncrementalTaskInputs.java:27)
	at org.gradle.api.tasks.incremental.IncrementalTaskInputs$outOfDate.call(Unknown Source)
	at com.apollographql.apollo.gradle.ApolloClassGenerationTask.generateClasses(ApolloClassGenerationTask.groovy:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 42 more
`

So I generated the file first time without any issue. But when I tried to change schema and build again it started to give me this error. Any idea ?

**Comment by tjouin** [comment]
Fix it by deleting Apollo and all file generated and implementing it again.

**Comment by ft9292** [comment]
I still can't fix this, even after removing and re-implementing apollo. @tjouin can you describe what you did exactly?

**Comment by ft9292** [comment]
I was using version `0.3.2` in the project gradle file, switched back to `0.3.1` and everything seems to be working fine, just noting to whoever runs in the same problem.
`classpath 'com.apollographql.apollo:gradle-plugin:0.3.1'

**Comment by brimanning** [comment]
I wanted to add that this happened to me as well using alpha3. While clearing caches, deleting generated files, cleaning the project, and restarting the machine did not fix the issue, downgrading to alpha2 did fix it. After building once with alpha2, switching back to alpha3 worked, so maybe there was something invalid still staying around through my attempts to clean everything.

**Comment by hborders** [comment]
This happened to me while using `1.0.0-alpha2`. I switched to `1.0.0-alpha3` and my build worked. I think reverted back down to `1.0.0-alpha2` and things worked again. 🤷‍♂️

**Comment by LybrialsGit** [comment]
Get the same problem but for:

`> java.io.FileNotFoundException: /Users/*/*/generated/source/apollo/generatedIR/main (Is a directory)`

And it is consistent. That means I get the error with any version.

**Comment by eoinahernBDSwiss** [comment]
i deleted apollo-codegen from the project. clean - rebuild. issue is still there. damn

**Comment by enoler** [comment]
The problem was solved for me downgrading the version of gradle. It was not working since I updated the gradle version to 5.1.1, and downgrading it to 4.10.2 worked again.

**Comment by okayan** [comment]
> java.io.FileNotFoundException: /Users/*/*/generated/source/apollo/generatedIR/main (Is a directory)

My project occurs same the error. but I deleted my project, clone my project from gitlab, and then build it, I can fix it.
