### ISSUE TITLE
Is there any way to resolve ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List?

### ISSUE THREAD

**Issue by buddhasaikia** [apollographql/apollo-android#1049]
I am getting this exception
>com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List

Here is the logcat output

`2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-09-07 17:15:05.378 15955-15955/com.packagename.dev W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err: Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:153)
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err:     at com.packagename.graphql.mutation.b.A$Data$Mapper.map(A.java:267)
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err:     at com.packagename.graphql.mutation.b.A$Data$Mapper.map(A.java:262)
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:96)
2018-09-07 17:15:05.379 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
2018-09-07 17:15:05.380 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:91)
2018-09-07 17:15:05.380 15955-15955/com.packagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
2018-09-07 17:15:05.380 15955-15955/com.packagename.dev W/System.err: 	... 7 more`

**Comment by sav007** [comment]
It seems it tries to read list `com.apollographql.apollo.internal.response.RealResponseReader.readList(` but somehow got a map, maybe wrong schema or server sends wrong type for the field. Could you please check the raw response for this field that causes this exception.

**Comment by buddhasaikia** [comment]
Thanks for quick reply. I will verify & let you know.

**Comment by sav007** [comment]
graphQlListOfListOfObjects
