### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Stack is empty.

### ISSUE THREAD

**Issue by buddhasaikia** [apollographql/apollo-android#1092]
Getting this exception. **(Version 1.0.0-alpha2)**
`
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-10-25 16:03:41.602 30521-30521/com.yourpackagename.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-10-25 16:03:41.603 30521-30521/com.yourpackagename.dev W/System.err:     at java.lang.Thread.run(Thread.java:760)
2018-10-25 16:03:41.603 30521-30521/com.yourpackagename.dev W/System.err: Caused by: java.lang.IllegalStateException: Stack is empty.
2018-10-25 16:03:41.603 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.util.SimpleStack.pop(SimpleStack.java:28)
2018-10-25 16:03:41.603 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer.didResolveList(ResponseNormalizer.java:97)
2018-10-25 16:03:41.603 30521-30521/com.yourpackagename.dev W/System.err:     at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:172)
2018-10-25 16:03:41.604 30521-30521/com.yourpackagename.dev W/System.err:     at com.yourpackagename.graphql.fragment.TerminalFragment$Mapper.map(TerminalFragment.java:193)`

**Comment by buddhasaikia** [comment]
I am unable to reproduce it. I will update the ticket when I face it next time.
