### ISSUE TITLE
Project does not compile without .graphql Files

### ISSUE THREAD

**Issue by moritzmorgenroth** [apollographql/apollo-android#1154]
When creating a new project and adding an introspection schema, the app throws a build error as follows: 
```
:app:checkDebugClasspath UP-TO-DATE
:app:preBuild
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:nodeSetup UP-TO-DATE
:app:installApolloCodegen UP-TO-DATE
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/Wingding/Documents/Programming/twigbit/vos/vos-client-android/app/build/apollo-codegen/node_modules/apollo-codegen/src/cli.js:186:16)
    at Object.runCommand (/Users/Wingding/Documents/Programming/twigbit/vos/vos-client-android/app/build/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/Wingding/Documents/Programming/twigbit/vos/vos-client-android/app/build/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/Wingding/Documents/Programming/twigbit/vos/vos-client-android/app/build/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/Wingding/Documents/Programming/twigbit/vos/vos-client-android/app/build/apollo-codegen/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
:app:generateDebugApolloIR FAILED
```
After adding an empty file `Query.graphql` to the `scr/main/graphql/` folder, the project compiles just fine. This should be fixed/caught in the generation process. 

I might create a PR if I find the source of this. Here is my configuration:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.11'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`
    implementation 'com.apollographql.apollo:apollo-runtime:1.0.0-alpha3'
`

**Comment by digitalbuddha** [comment]
I see this as a feature rather than a bug.  Users should be forced to have at least 1 valid query in a valid location.  If this gets disabled then we run into the risk of a query being placed in the wrong location and no user feedback given
