### ISSUE TITLE
NPE in ApolloServerInterceptor

### ISSUE THREAD

**Issue by parthmg** [apollographql/apollo-android#1164]
We ase getting NPE in ApolloServerInterceptor

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void o.QC.ˋ(o.QB)' on a null object reference
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run(SourceFile:84)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

This is the crash log for the same.

What could be the reason for this, we are seeing many crashes because of this

Edit: 
SDK version used is 0.4.3

**Comment by digitalbuddha** [comment]
Please update to latest version. If issue still persists, create a failing test case or sample project showing the issue
