### ISSUE TITLE
 com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response

### ISSUE THREAD

**Issue by xiaofengshen** [apollographql/apollo-android#1184]
`subscription RepoCommentAddedSubscription($repo: String!) {
  commentAdded(repoFullName: $repo) {
    id
    content
  }
}`
` {"data":{"table_mall_goods_all":[{"__typename":"table_mall_goods_all","goods_name":"甘堡藏寨、毕棚沟一日游温泉雪山红叶精华游"}, {"__typename":"table_mall_goods_all","goods_name":"<真正纯玩0购物+赠云中贡嘎晚会>成都至甘孜海螺沟+泸定桥磨西古镇3日游  "}, {"__typename":"table_mall_goods_all","goods_name":"【跟团游】都江堰-青城山-毕棚沟-甘堡藏寨-桃坪羌寨双汽3日游，享篝火晚会，赠景区温泉"}]}}`

`
    ApolloCall<TravelHomepageQuery.Data> subscriptionCall = application.apolloClient()
        .query(new TravelHomepageQuery());

    subscriptionCall.enqueue(dataCallback);

  }
  private ApolloCall.Callback<TravelHomepageQuery.Data> dataCallback
      = new ApolloCallback<>(new ApolloCall.Callback<TravelHomepageQuery.Data>() {
      @Override public void onResponse(@NotNull Response<TravelHomepageQuery.Data> response) {
        Log.i("TAG",response.data().toString());

      }

    @Override public void onFailure(@NotNull ApolloException e) {
      Log.e(TAG, e.getMessage(), e);
    }
  }, uiHandler);`

**retrun error**
`Failed to parse http response
                                                                              com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:96)
                                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                  at java.lang.Thread.run(Thread.java:764)
                                                                               Caused by: java.lang.IllegalStateException: closed
                                                                                  at okio.RealBufferedSource.request(RealBufferedSource.java:66)
                                                                                  at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.nextNonWhitespace(BufferedSourceJsonReader.java:897)
                                                                                  at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:332)
                                                                                  at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)
                                                                                  at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:82)
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
                                                                                  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:96) 
                                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                  at java.lang.Thread.run(Thread.java:764) `

**Comment by creativedrewy** [comment]
Just to add to this issue, I too saw this with alpha4. It would seem every call returns both valid data and a 502.

Bumping all the "implementation" dependencies back to alpha3 made things work just fine.

**Comment by xiaofengshen** [comment]
I already "implementation" dependencies   alpha3,but the problem can't solve.

**Comment by sav007** [comment]
We had issue with the SHA of query generation, that made some server implementations to cancel connection, but it was fixed in snapshot version, could you pls try snapshot version and let me know if you still the issue.

**Comment by xiaofengshen** [comment]
I used "ext.apolloReleaseVersion = '1.0.0-alpha3'"

**Comment by sav007** [comment]
could you pls try latest snapshot version

**Comment by sav007** [comment]
Closing.
