### ISSUE TITLE
CodegenTest.tk fails with NoSuchMethodError okio.BufferedSource.getBuffer()Lokio/Buffer;

### ISSUE THREAD

**Issue by venik** [apollographql/apollo-android#1210]
Hi, Im trying to run UT from AndroidStudio and CodegenTest.tk fails with
```
java.lang.NoSuchMethodError: okio.BufferedSource.getBuffer()Lokio/Buffer;

	at com.squareup.moshi.JsonUtf8Reader.<init>(JsonUtf8Reader.java:97)
	at com.squareup.moshi.JsonReader.of(JsonReader.java:196)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:40)
	at com.apollographql.apollo.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:16)
	at com.apollographql.apollo.compiler.CodeGenTest.generateExpectedClasses(CodegenTest.kt:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

looks similar to
https://github.com/square/moshi/issues/740

It looks like Moshi depends on okio 1.16.0 and it should work, I'm slightly confused.

Thanks in advance

**Comment by rafalzawadzki** [comment]
@venik have you found a solution? I am facing the same problem, and fiddling with moshi/okio versions seems to not work.

**Comment by rafalzawadzki** [comment]
I found out the issue, I think it's rather project specific than a problem with Apollo.

In our project we are using additional Kotlin DSL for managing dependencies. I did not notice that we pulled in OkHttp version 3.12.0 there. Even though I tried forcing specific versions in build.gradle, the dsl was pulling in dependencies on it's own. After upgrading OkHttp to 4.1.0 the problem resolved.
