### ISSUE TITLE
Compile-time Error: Type com.apollographql.apollo.cache.normalized.NormalizedCacheFactory is referenced as an interface from `com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory`.

### ISSUE THREAD

**Issue by saurabhdtu** [apollographql/apollo-android#1281]
Getting this error while compiling
**Type com.apollographql.apollo.cache.normalized.NormalizedCacheFactory is referenced as an interface from `com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory`.**

I am using version 1.0.0-alpha5.
Gradle Version - 5.1.1
Android Studio - 3.4
I have disabled r8 shrinker
The issue seems similar to this - [found while researching for the solution](https://github.com/mapbox/mapbox-gl-native/issues/12987),
[Or maybe this one](https://github.com/apollographql/apollo-android/issues/664)

`Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/saurabh/.gradle/caches/transforms-2/files-2.1/6f1e3bc6d8f650ec2faa1b46e1ab168e/jars/classes.jar`
`Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing`
`Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete`
`Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.apollographql.apollo.cache.normalized.NormalizedCacheFactory is referenced as an interface from com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory.`

**_Here is the detailed error stacktrace for the same:-_**

`org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
	<79 internal calls>`

`Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
	<30 internal calls>`

`Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/saurabh/.gradle/caches/transforms-2/files-2.1/6f1e3bc6d8f650ec2faa1b46e1ab168e/jars/classes.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	<60 internal calls>`

`Caused by: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/saurabh/.gradle/caches/transforms-2/files-2.1/6f1e3bc6d8f650ec2faa1b46e1ab168e/jars/classes.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:442)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 68 more
Caused by: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/saurabh/.gradle/caches/transforms-2/files-2.1/6f1e3bc6d8f650ec2faa1b46e1ab168e/jars/classes.jar
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:149)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:420)
	... 71 more`

`Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/saurabh/.gradle/caches/transforms-2/files-2.1/6f1e3bc6d8f650ec2faa1b46e1ab168e/jars/classes.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
	at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)`
	... 1 more`

`Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:70)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:94)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
	... 2 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.apollographql.apollo.cache.normalized.NormalizedCacheFactory is referenced as an interface from `com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory`.
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
	... 5 more`

**Comment by gagan2017** [comment]
What was the solution

**Comment by ilyabaykalov** [comment]
I have same problem. What was the solution??
