### ISSUE TITLE
Unit test with coroutines

### ISSUE THREAD

**Issue by heitorcolangelo** [apollographql/apollo-android#1292]
Hey guys!
I'm trying to test a simple implementation that it's using `apollo-coroutine-support` to perform the query.
That's the code:
```kotlin
internal class UsersApiImpl(
        private val client: ApolloClient,
        private val usersQueryBuilder: UsersByIdQuery.Builder
) : UsersApi {

    @WorkerThread
    override suspend fun getUsers(usersIds: List<String>): Response<UsersByIdQuery.Data> {
        val query = usersQueryBuilder
                .ids(usersIds)
                .build()

        return client.query(query).toDeferred().await()
    }
}
```
That's the test:
```kotlin
@RunWith(JUnit4::class)
class UsersApiTest {

    @RelaxedMockK private lateinit var client: ApiClient
    @RelaxedMockK private lateinit var query: UsersByIdQuery.Builder
    private lateinit var api: UsersApi

    @Before
    fun setUp() {
        MockKAnnotations.init(this)

        api = UsersApiImpl(client, query)
    }

    @Test
    fun getUsers_shouldRequestUsersFromApi() {
        val ids = listOf("1", "2", "3", "4")

        val call = mockk<ApolloQueryCall<UsersByIdQuery.Data>>("callMock")

        every {
            client.getClient().query(query.build())
        } returns call

        val deferred = mockk<Deferred<Response<UsersByIdQuery.Data>>>("deferredMock")

        every {
            call.toDeferred()
        } returns deferred

        val dataMock = mockk<Response<UsersByIdQuery.Data>>("dataMock")

        every {
            runBlocking {
                deferred.await()
            }
        } returns dataMock

        // The error happens here
        runBlocking {
            api.getUsers(ids)
        }

        verify {
            query.ids(ids)
            query.build()
        }
    }
}
```

Using only `runBlocking` makes the test running forever, it never finishes.
Using `runBlockingTest` from `org.jetbrains.kotlinx:kotlinx-coroutines-test` I got this exception:

```
java.lang.IllegalStateException: This job has not completed yet

	at kotlinx.coroutines.JobSupport.getCompletionExceptionOrNull(JobSupport.kt:1114)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:53)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
	at com.mypackage.data.UsersApiTest.getUsers_shouldRequestUsersFromApi(UsersApiTest.kt:63)
```

The code works, but I'm not being able to test it.
Does anyone have any idea why is this happening? I'm still not sure if it's something wrong with the way I'm using `apollo-coroutine-support` or if it's something with how I am using coroutines itself.

**Comment by heitorcolangelo** [comment]
So after almost 2 days on this, I had to add this to my test:
```kotlin
val responseData = mockk<Response<UsersByIdQuery.Data>>()
every {
    responseData.data()
} returns mockk()

val slot = CapturingSlot<ApolloCall.Callback<UsersByIdQuery.Data>>()
every { call.enqueue(capture(slot)) } answers {
    slot.captured.onResponse(responseData)
}
```

And then the final test is
```kotlin
@Test
fun getUsers_shouldRequestUsersFromApi() = runBlocking {
    val ids = listOf("1", "2", "3", "4")

    every {
        queryBuilder.ids(any())
    } returns queryBuilder

    val query = mockk<UsersByIdQuery>()
    every {
        queryBuilder.build()
    } returns query

    val call = mockk<ApolloQueryCall<UsersByIdQuery.Data>>()
    every {
        client.query(query)
    } returns call

    val responseData = mockk<Response<UsersByIdQuery.Data>>()
    every {
        responseData.data()
    } returns mockk()

    val slot = CapturingSlot<ApolloCall.Callback<UsersByIdQuery.Data>>()
    every { call.enqueue(capture(slot)) } answers {
        slot.captured.onResponse(responseData)
    }

    api.getUsers(ids)

    verify {
        queryBuilder.ids(ids)
        queryBuilder.build()

        client.query(query)
        call.enqueue(any())
    }
}
```

I'm not sure if this should be considered an issue, so I'm closing it for now.

**Comment by digitalbuddha** [comment]
Thanks for following up with your working impl. Since it was a third party library I don't think any action is needed at this time

**Comment by janis91** [comment]
Btw: another approach, which makes it easier to mock the `toDeferred` call directly is described here:
https://mockk.io/#extension-functions
You'd have to use `mockkStatic("com.apollographql.apollo.coroutines.CoroutinesExtensionsKt")`, because it's a module wide extension function that should be mocked.

After that you can simply do:
```kotlin
every {
    call.toDeferred()
} returns deferred
```
