### ISSUE TITLE
Kotlin code gen generating incorrect nullability

### ISSUE THREAD

**Issue by ZacSweers** [apollographql/apollo-android#1300]
I get the following null parameter runtime failure in generated kotlin code for talking to GitHub's API.

Repro project (at the specific sha): https://github.com/ZacSweers/CatchUp/tree/158d1bce26bcfe9a195fb82d9fd9bb45f77deb75
Build and run the app (`./gradlew :app:installDebug`) and navigate to settings -> About to get the crash. Note that this requires having a github API key (set via gradle property `catchup_github_developer_token` or manually in `app/build.gradle.ktx`)

Stacktrace

```
2019-05-15 04:10:08.847 5058-5215/io.sweers.catchup.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp https://api.github.com/...
    Process: io.sweers.catchup.debug, PID: 5058
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.innerError(ObservableFlatMapSingle.java:204)
        at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver$InnerObserver.onError(ObservableFlatMapSingle.java:289)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onError(ObservableElementAtSingle.java:102)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
        at com.apollographql.apollo.rx2.Rx2Apollo$2$1.onFailure(Rx2Apollo.java:100)
        at com.apollographql.apollo.ApolloCall$Callback.onParseError(ApolloCall.java:122)
        at com.apollographql.apollo.internal.RealApolloCall$1.onFailure(RealApolloCall.java:250)
        at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onFailure(ApolloCacheInterceptor.java:91)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onFailure(ApolloParseInterceptor.java:63)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:57)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:106)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:106) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at io.sweers.catchup.data.github.RepositoryByNameAndOwnerQuery.wrapData(Unknown Source:2)
        at io.sweers.catchup.data.github.RepositoryByNameAndOwnerQuery.wrapData(RepositoryByNameAndOwnerQuery.kt:25)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:107)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:106) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by sav007** [comment]
@ZacSweers Original issues was fixed in snapshot version. But running your sample app I'm getting this error returned by Github GraphQL server (and that was the trigger of this issue):
```
{"errors":[{"message":"No operation named \"RepositoryByNameAndOwnerQuery\""}]}
```

Trying to investigate why.

Btw app crashing anyway in this function io.sweers.catchup.ui.about.ChangelogFragment#requestItems:
```
return Rx2Apollo.from(apolloClient.query(RepoReleasesQuery()))
        .flatMapIterable { it.data()!!.repository!!.releases.nodes }
```

Keep in mind that `data` is nullable, in case of error you should  check for `it.errors`

**Comment by sav007** [comment]
Oh ok found, seems we send `operationName` different from the actual `queryName`. Going to fix this.

**Comment by sav007** [comment]
Fixed.

**Comment by ZacSweers** [comment]
woo!
