### ISSUE TITLE
Adding `normalizedCache` causes IllegalStateException with `Stack is empty.` exception when `LIST` has `null` elements

### ISSUE THREAD

**Issue by hborders** [apollographql/apollo-android#1301]
I'm running `com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha5` and `com.apollographql.apollo:apollo-runtime:1.0.0-alpha5`.

When using a `normalizedCache` to build my `ApolloClient`, I get the following stack trace:
```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Stack is empty.
        at com.apollographql.apollo.internal.util.SimpleStack.pop(SimpleStack.java:28)
        at com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer.didResolveList(ResponseNormalizer.java:97)
        at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:172)
        at autogenerated.BrokenQuery$Data$Mapper.map(BrokenQuery.java:164)
        at autogenerated.BrokenQuery$Data$Mapper.map(BrokenQuery.java:159)
        at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:96)
        at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:91)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

When parsing the following response:
```
{
  "data":{
    "foos":[
      null,
      {
        "__typename": "Foo",
        "fizz": "asdf"
      }
    ]
  }
}
```

For the following query:
```
query BrokenQuery {
  foos {
    fizz
  }
}
```

I've isolated this in a minified project for you at https://github.com/hborders/apollo-bug-stack-empty

This seems like it could be related to https://github.com/apollographql/apollo-android/issues/1092 and https://github.com/apollographql/apollo-android/issues/542

**Comment by hborders** [comment]
It looks like this was fixed in https://github.com/apollographql/apollo-android/pull/1211 which was released as part of [`v1.0.0`](https://github.com/apollographql/apollo-android/releases/tag/1.0.0)

I started investigating this on Friday, and Android Studio told me that `1.0.1-SNAPSHOT` was available instead of `1.0.0-alpha5`, but I wasn't my repo couldn't download `1.0.1-SNAPSHOT`, so I didn't know that `1.0.0` existed. Also, I guess it wasn't officially created until 2 days ago. Anyway, I hope this history helps someone else, at least. :)
