### ISSUE TITLE
Empty .graphql package fails build with cryptic message

### ISSUE THREAD

**Issue by dlleixap** [apollographql/apollo-android#1337]
Hi there Apollo team! After setting up everything in a new project(a copy/paste from a previous one I had working just fine), I tried to build the code and got the error below. The fix was as simple as to add a `foo.graphql` file with a query in the `.graphql` package. Basically, apollo complained about having a schema.json and a full apollo setup but without a single query/mutation in the project. It would be great to have a message pointing out this case.
Cheers, thanks and keep up the good work!

```
> Task :partners-network:generateMainApolloIR FAILED
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/dlleixa/Wayfair/waystation-app/android/partners-network/build/apollo-codegen/node_modules/apollo-codegen/src/cli.js:186:16)
    at Object.runCommand (/Users/dlleixa/Wayfair/waystation-app/android/partners-network/build/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/dlleixa/Wayfair/waystation-app/android/partners-network/build/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/dlleixa/Wayfair/waystation-app/android/partners-network/build/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/dlleixa/Wayfair/waystation-app/android/partners-network/build/apollo-codegen/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':partners-network:generateMainApolloIR'.
> Process 'command '/Users/dlleixa/Wayfair/waystation-app/android/partners-network/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
