### ISSUE TITLE
It‘s’ supporting HTTPS only  ？

### ISSUE THREAD

**Issue by xiaozhao0331** [apollographql/apollo-android#1408]
My BaseUrl is HTTP type and then there's this error. but  when i check the response . It is turly Json .  What should I do?

 com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response   at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101) at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:96) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.apollographql.apollo.json.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $ at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.syntaxError(BufferedSourceJsonReader.java:1062) at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.checkLenient(BufferedSourceJsonReader.java:954) at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:379)  at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:82)at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:96)  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedR.....

**Comment by sav007** [comment]
Well there is an issue in the response `Caused by: com.apollographql.apollo.json.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $ at ` There is not much I can help with, please double check that it's valid json response

**Comment by xiaozhao0331** [comment]
Thanks for you reply.Sorry . It is  my mistake .Finally  I find the problem was  the online debug url is “http://xxxx:xxxxx/graphiql”. It  diffent with the BASE_URL .
