### ISSUE TITLE
Cannot read a fragment from the QUERY_ROOT

### ISSUE THREAD

**Issue by freshtonic** [apollographql/apollo-android#1440]
Imagine I have a query like so:

```graphql
query {
  __typename
  people {
    __typename
   id
   email
  }
}
```

And I execute the query which puts the result in the local store.

And let's say I have a fragment like this:

```graphql
fragment PeopleFragment on Query {
    __typename
    people {
        id
       email
    }
}
```

And I try to read that fragment from the store (using the generated fragment class):

```java
PeopleFragment peopleFragment = client().apolloStore().read(
  new PeopleFragment.Mapper(),
  CacheKey.from("QUERY_ROOT"), 
  EMPTY_VARIABLES
).execute();
```

I see a null pointer exception:

```
   Caused by: java.lang.NullPointerException: Missing value: __typename
        at com.apollographql.apollo.internal.field.CacheFieldValueResolver.fieldValue(CacheFieldValueResolver.java:101)
        at com.apollographql.apollo.internal.field.CacheFieldValueResolver.valueFor(CacheFieldValueResolver.java:43)
        at com.apollographql.apollo.internal.field.CacheFieldValueResolver.valueFor(CacheFieldValueResolver.java:16)
```

The root cause of the exception is the attempt to read a `__typename` field when reading the fragment from the cache. I suspect that because in my case the fragment is on the query root and there's no `__typename` there, then that is my problem.

```java
public PeopleFragment map(ResponseReader reader) {
      final String __typename = reader.readString($responseFields[0]); // blows up
      // ...
```

The following keys are in the store:

```
 Person.18970480.id,
 Person.18933274.id,
 Person.18970480.email,
 Person.18933274.email,
 Person.18970480.__typename,
 Person.18933274.__typename,
 QUERY_ROOT.people
```

**Comment by freshtonic** [comment]
So I guess, how do I make this work? Do I have to somehow arrange for the `QUERY_ROOT` to have a `__typename` entry in the store?

**Comment by sav007** [comment]
Not sure if this possible but the correct key is probably `query ` not `QUERY_ROOT`.
Could you please dump the cache (memory cache):
```
Map<Class, Map<String, Record>> dump = apolloClient.apolloStore().normalizedCache().dump();
String dumpStr = NormalizedCache.prettifyDump(dump)
```
So you can see how it stored.

**Comment by freshtonic** [comment]
@sav007 no, the key is `QUERY_ROOT`.

```
"QUERY_ROOT" : {
        "people" : [
          ...
         ]
}
```

**Comment by sav007** [comment]
Could you please dump the cache so I can see the whole picture.

**Comment by sav007** [comment]
Closing due to inactivity.
