### ISSUE TITLE
Returntype for encode and decode in CustomTypeAdapter (FileUpload)

### ISSUE THREAD

**Issue by jaaveeth17** [apollographql/apollo-android#1471]
I am trying to implement File upload and here is my below code,

As per documentation, I have added customtype adapter in my apolloclient

apolloClient = ApolloClient.builder()
                .serverUrl(Constants.APOLLO_URL)
                .addCustomTypeAdapter(CustomType.UPLOAD,new UploadCustomTypeAdapter())
                .okHttpClient(okHttpClient)
                .build();

Here is my CustomTypeAdapter class,

class UploadCustomTypeAdapter implements CustomTypeAdapter<FileUpload> {

    @Override
    public FileUpload decode(@NotNull CustomTypeValue value) {
        return null;  // what is the return type to be mentioned here
    }

    @NotNull
    @Override
    public CustomTypeValue encode(@NotNull FileUpload value) {
        return null;  // what is the return type to be mentioned here
    }
}

Please tell me what to return in the above encode and decode method. I tried and implemented 
many ways but couldn't resolve.

**Comment by sav007** [comment]
Oh, we missed that part in the docs.

So `FileUpload ` is kind of special custom type, you don't need to register any adapter it will be handled internally.

**Comment by sav007** [comment]
Actually we need to update docs.

**Comment by jaaveeth17** [comment]
Thanks for the immediate response. I initially didn't include any custom adapter but the following error made me create an adapter. Please have a look ,

2019-08-03 03:30:51.220 10389-10477/com.popjob.user E/AndroidRuntime: FATAL EXCEPTION: Apollo Dispatcher
    Process: com.popjob.user, PID: 10389
    java.lang.IllegalArgumentException: Can't map GraphQL type: Upload to: class com.apollographql.apollo.api.FileUpload. Did you forget to add custom type adapter?
        at com.apollographql.apollo.response.ScalarTypeAdapters.adapterFor(ScalarTypeAdapters.java:29)
        at com.apollographql.apollo.internal.json.InputFieldJsonWriter.writeCustom(InputFieldJsonWriter.java:87)
        at com.popjob.user.AddCategoryMutation$Variables$1.marshal(AddCategoryMutation.java:160)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpPostRequestBody(ApolloServerInterceptor.java:185)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpPostCall(ApolloServerInterceptor.java:134)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run(ApolloServerInterceptor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by chalermpong** [comment]
The file upload feature is available since version 1.0.1.
Seem like you're using the version older than that, otherwise the error should be thrown from `ScalarTypeAdapters.java:30`

**Comment by jaaveeth17** [comment]
Hey, @chalermpong thanks for the information. Yes, I was using the older version. Now I have changed all the plugin and dependencies up to date (1.02) and it's working perfectly. 

Once again thank you @sav007 and @chalermpong for taking the time to respond.
