### ISSUE TITLE
Execution failed for task ':app:installApolloCodegen'.

### ISSUE THREAD

**Issue by xghita** [apollographql/apollo-android#1517]
```
 Task :app:installApolloCodegen FAILED
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-ge
neration for more information.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Ghita\\Documents\\android life\\projects\\cofe-app\\app\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe" "C:\\Users\\Ghita\\Documents\\android life\\projects\\cofe-app\\app\\.gradle\\n
odejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "apollo-codegen@0.19.1" "--save" "--save-exact"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file C:\Users\Ghita\AppData\Roaming\npm-cache\apollo-codegen\0.19.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\Ghita\AppData\Roaming\npm-cache\apollo-codegen\0.19.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ghita\Documents\android life\projects\cofe-app\app\build\apollo-codegen\npm-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installApolloCodegen'.
> Process 'command 'C:\Users\Ghita\Documents\android life\projects\cofe-app\app\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:installApolloCodegen'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
        at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
```
 why is my _package.json_ from apollo-codegen folder empty?
i am new to graphql, and i don't understand exactly what is this error and how should i fixed it

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

**Comment by kangyun9957** [comment]
did you solve this problem? plz help me

**Comment by martinbonnin** [comment]
@kangyun9957 `apollo-codegen` is not used anymore, the error should go away if you upgrade to a more recent version of `apollo-android`
