### ISSUE TITLE
GenerateApolloClasses failed with missing method exception

### ISSUE THREAD

**Issue by japplin** [apollographql/apollo-android#1553]
Trying to update from 1.0.2 to 1.1.1 
When running `generateApolloClasses` I'm getting this build error:
```
> Task :generateDebugApolloClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDebugApolloClasses'.
> com.squareup.moshi.JsonReader.peekJson()Lcom/squareup/moshi/JsonReader;
```
This snippet of --stacktrace seems relevant:
```
Caused by: java.lang.NoSuchMethodError: com.squareup.moshi.JsonReader.peekJson()Lcom/squareup/moshi/JsonReader;
        at com.apollographql.apollo.compiler.parser.Schema$Companion.locateSchemaRootNode(Schema.kt:163)
        at com.apollographql.apollo.compiler.parser.Schema$Companion.parse(Schema.kt:143)
        at com.apollographql.apollo.compiler.parser.Schema.parse(Schema.kt)
        at com.apollographql.apollo.compiler.parser.Schema$parse.call(Unknown Source)
        at com.apollographql.apollo.gradle.ApolloExperimentalCodegenTask.generateClasses(ApolloExperimentalCodegenTask.groovy:50)
```

**Comment by martinbonnin** [comment]
It looks like you have an older moshi dependency in your buildscript classpath. apollo-android depends o moshi 1.8.0. 

Can you try running  `./gradlew buildEnvironment` ? Does that give any info ?

**Comment by martinbonnin** [comment]
Thanks! It looks like moshi is resolved to `1.8.0` correctly... At least by the `buildEnvironment`. I'm not an expert of gradle class loading but it really looks like a wrong version of `moshi` is loaded though. 

Maybe try to remove other plugins than apollo-android to see if it helps ?

**Comment by martinbonnin** [comment]
Thanks for the follow up.

**Comment by sav007** [comment]
I guess we can close it.

**Comment by DSteve595** [comment]
I'm getting this same error, and `buildEnvironment` shows the only dependency that needs Moshi is `apollo-gradle-plugin:1.1.3`. No other mentions of Moshi.
