### ISSUE TITLE
Conditional Fragment with Required Field Causes Parse Issue

### ISSUE THREAD

**Issue by justincamp404** [apollographql/apollo-android#1584]
Greetings!

I'm having an issue with a conditional fragment that contains a required field causing parse errors. Details (snipped for brevity) below:

Query:
```
query StoryAnswerQuery ($relayId: String!) {
    me {
        storyAnswer(relayId: $relayId) {
            answerer {
                ... DefaultUserFields
                createdAt
            }
    }
}
fragment DefaultUserFields on User {
    id
    name
}
```

the answerer field (I'm hoping User & Organization are self-explanitory):
```
union Answerer = User | Organization
```

Error:
```
2019-09-12 13:55:36.669 10397-10397/com.app E/NotificationViewHolder: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:125)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: corrupted response reader, expected non null value for id
        at com.apollographql.apollo.internal.response.RealResponseReader.checkValue(RealResponseReader.java:264)
        at com.apollographql.apollo.internal.response.RealResponseReader.readCustomType(RealResponseReader.java:187)
        at com.app.graphql.fragment.DefaultUserFields$Mapper.map(DefaultUserFields.java:187)
        at com.app.graphql.StoryAnswerQuery$Answerer$Fragments$Mapper.map(StoryAnswerQuery.java:920)
        at com.app.graphql.StoryAnswerQuery$Answerer$Mapper$1.read(StoryAnswerQuery.java:935)
        at com.app.graphql.StoryAnswerQuery$Answerer$Mapper$1.read(StoryAnswerQuery.java:932)
        at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:228)
        at com.app.graphql.StoryAnswerQuery$Answerer$Mapper.map(StoryAnswerQuery.java:932)
        at com.app.graphql.StoryAnswerQuery$StoryAnswer$Mapper$1.read(StoryAnswerQuery.java:722)
        at com.app.graphql.StoryAnswerQuery$StoryAnswer$Mapper$1.read(StoryAnswerQuery.java:719)
        at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)
        at com.app.graphql.StoryAnswerQuery$StoryAnswer$Mapper.map(StoryAnswerQuery.java:719)
        at com.app.graphql.StoryAnswerQuery$Me$Mapper$1.read(StoryAnswerQuery.java:378)
        at com.app.graphql.StoryAnswerQuery$Me$Mapper$1.read(StoryAnswerQuery.java:375)
        at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)
        at com.app.graphql.StoryAnswerQuery$Me$Mapper.map(StoryAnswerQuery.java:375)
        at com.app.graphql.StoryAnswerQuery$Data$Mapper$1.read(StoryAnswerQuery.java:275)
        at com.app.graphql.StoryAnswerQuery$Data$Mapper$1.read(StoryAnswerQuery.java:272)
        at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)
        at com.app.graphql.StoryAnswerQuery$Data$Mapper.map(StoryAnswerQuery.java:272)
        at com.app.graphql.StoryAnswerQuery$Data$Mapper.map(StoryAnswerQuery.java:267)
        at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:96)
        at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:91)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:125) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

This occurs when an Organization is the "answerer" and there is no User data. Of course, it works fine when a User is the answerer.

If I remove the id attribute from the fragment, all is well (but of course, I need that id). Also, if I put inline fragments, no fields are generated at all for the inline fragment. Looking at the generated code, inline fragments generate the AsUser|AsOrganization mappings as expected, but there's no field to reference to actually get to the data...

**Comment by sav007** [comment]
Could you please attach the generated models for `StoryAnswerQuery ` and `DefaultUserFields `?

**Comment by tjaksa** [comment]
I have experienced the same problem. I generated a simple sample that has the problem and attached the generated files. In my case, the MediaOnLobby fragment has a required field (created) that throws a null pointer exception when a VideoOnLobby is actually present
. I also noticed that version 1.1.3 attempts to decode each possible fragment type while version 1.0.0 only attempted to decode fragments that matched the proper __typename(s).
[Sample.zip](https://github.com/apollographql/apollo-android/files/3633458/Sample.zip)

**Comment by justincamp404** [comment]
Absolutely!

The problem clearly is that one of the unioned fragments asks for an id, and one does not, yet both are parsed regardless of the type.
[sources.zip](https://github.com/apollographql/apollo-android/files/3637047/sources.zip)

**Comment by sav007** [comment]
Hey folks, super weird issue that I couldn't reproduce on our test fixtures. Could anyone share schema.json with me, so I can try to reproduce with your query sample?

**Comment by sav007** [comment]
Never mind I was able to reproduce, fix is coming.
