### ISSUE TITLE
Main Thread remains blocked by the ApolloServerInterceptor

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#1647]
Sometimes running a query using apollo results in the application getting an anr caused by the ApolloServerInterceptor 

```
"main@3653" prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OkHttp https://streaming-api-bar/...@4905 to release lock on <0x2229> (a com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor)
	  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.dispose(ApolloServerInterceptor.java:90)
	  at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.dispose(RealApolloInterceptorChain.java:42)
	  at com.apollographql.apollo.internal.RealApolloCall.cancel(RealApolloCall.java:187)
	  - locked <0x2228> (a com.apollographql.apollo.internal.RealApolloCall)
	  at com.apollographql.apollo.rx2.Rx2Apollo$6.dispose(Rx2Apollo.java:232)
	  at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
	  at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:121)
	  at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
	  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.dispose(ObservableSubscribeOn.java:73)
	  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
	  at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
	  at io.reactivex.observers.DisposableObserver.dispose(DisposableObserver.java:91)
	  at com.ownzones.app.ui.accountsettings.AccountSettingsActivityViewModel$makeUpdateUserInfoCall$observer$1.onNext(AccountSettingsActivityViewModel.kt:110)
	  at com.ownzones.app.ui.accountsettings.AccountSettingsActivityViewModel$makeUpdateUserInfoCall$observer$1.onNext(AccountSettingsActivityViewModel.kt:99)
	  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	  at android.os.Handler.handleCallback(Handler.java:739)
	  at android.os.Handler.dispatchMessage(Handler.java:95)
	  at android.os.Looper.loop(Looper.java:145)
	  at android.app.ActivityThread.main(ActivityThread.java:6939)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at java.lang.reflect.Method.invoke(Method.java:372)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by nicusorflorin** [comment]
another run has it blocked in RealApolloCall 
```
"OkHttp https://streaming-api-consumer.external.newstaging.ownzones.dev/...@4924" daemon prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for main@3652 to release lock on <0x22c1> (a com.apollographql.apollo.internal.RealApolloCall)
	  at com.apollographql.apollo.internal.RealApolloCall.terminate(RealApolloCall.java:359)
	  at com.apollographql.apollo.internal.RealApolloCall$1.onCompleted(RealApolloCall.java:264)
	  at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:86)
	  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:54)
	  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:125)
	  at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	  at com.ownzones.androidnet.network.SyncedExecutorService.execute(SyncedExecutorService.java:49)
	  at okhttp3.RealCall$AsyncCall.executeOn(RealCall.kt:117)
	  at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:181)
	  at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:122)
	  at okhttp3.RealCall.enqueue(RealCall.kt:78)
	  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.executeHttpCall(ApolloServerInterceptor.java:116)
	  - locked <0x22c2> (a com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor)
	  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run(ApolloServerInterceptor.java:84)
	  at com.ownzones.androidnet.network.SyncedExecutorService.execute(SyncedExecutorService.java:49)
	  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.interceptAsync(ApolloServerInterceptor.java:82)
	  at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceedAsync(RealApolloInterceptorChain.java:36)
	  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.interceptAsync(ApolloParseInterceptor.java:49)
	  at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceedAsync(RealApolloInterceptorChain.java:36)
	  at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1.run(ApolloCacheInterceptor.java:69)
	  at com.ownzones.androidnet.network.SyncedExecutorService.execute(SyncedExecutorService.java:49)
	  at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor.interceptAsync(ApolloCacheInterceptor.java:54)
	  at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceedAsync(RealApolloInterceptorChain.java:36)
	  at com.apollographql.apollo.internal.fetcher.NetworkOnlyFetcher$NetworkOnlyInterceptor.interceptAsync(NetworkOnlyFetcher.java:27)
	  at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceedAsync(RealApolloInterceptorChain.java:36)
	  at com.apollographql.apollo.internal.RealApolloCall.enqueue(RealApolloCall.java:147)
	  at com.apollographql.apollo.rx2.Rx2Apollo$2.subscribe(Rx2Apollo.java:90)
	  at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	  at io.reactivex.Observable.subscribe(Observable.java:12267)
	  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	  at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:818)
```

**Comment by sav007** [comment]
Looks like a deadlock here.

**Comment by sav007** [comment]
@nicusorflorin could you please provide sample of how you set-up Apollo client and how you build query to execute?
