### ISSUE TITLE
ApolloSubscriptionCall - Failed to parse server message

### ISSUE THREAD

**Issue by dualcnhq** [apollographql/apollo-android#1767]
**Summary**

The `localizedMessage` from ApolloException response message: `Failed to parse server message` is not that helpful in debugging the error.

**Description**

I'm trying to do a subscriptionCall and I'm using Hasura as the backend server, I followed and copy pasted pieces of code and modified it based on my schema from here: 
`https://learn.hasura.io/graphql/android/subscriptions/1-subscription`

The queries and the subscriptions are working on Hasura's dashboard and the other client web app that I'm using.
So I tried to do a basic queryCall using apollo-android and it's working, but the subscriptionCall keeps on failing.

Here's a snippet from my code:
```
newOrdersSubscription?.execute(object :
      ApolloSubscriptionCall.Callback<NewOrdersSubscription.Data> {
      override fun onFailure(e: ApolloException) {
        Log.d(TAG, "onFailure: ${e.localizedMessage}")
      }

      override fun onResponse(response: Response<NewOrdersSubscription.Data>) {
        Log.d(TAG, response.data().toString())
      }

      override fun onConnected() {
        Log.d(TAG, "onConnected: Connected to WS")
      }

      override fun onTerminated() {
        Log.d(TAG, "onTerminated: Disconnected from WS")
      }

      override fun onCompleted() {
        Log.d(TAG, "onFailure: Connection completed")
      }
    })
```

Is there other way how to debug this?

**Version**

```
implementation 'com.apollographql.apollo:apollo-runtime:1.2.0'
implementation "com.apollographql.apollo:apollo-android-support:1.2.0"

implementation 'com.squareup.okhttp3:okhttp:4.2.1'
implementation 'com.squareup.okhttp3:logging-interceptor:3.13.1'
```

**Comment by sav007** [comment]
Could you please print the whole stacktrace of the error? The actual error is attached in `cause` field, see `java.lang.Throwable#getCause`

**Comment by dualcnhq** [comment]
@sav007 I just have this from LogCat
```
D/OkHttp: <-- 101 Switching Protocols https://graph.api.mydomain.com/v1/graphql (1610ms)
D/OkHttp: Connection: Upgrade
D/OkHttp: Upgrade: websocket
D/OkHttp: Sec-Websocket-Accept: Xrm5w0wEsDGYPGLnEuh2nhhIlXs=
D/OkHttp: Sec-Websocket-Protocol: graphql-ws
D/OkHttp: Via: 1.1 vegur
D/OkHttp: <-- END HTTP
D/MainActivity: onConnected: Connected to WS
D/MainActivity: onConnected: Connected to WS
D/MainActivity: onFailure: Failed to parse server message
D/MainActivity: onFailure: Failed to parse server message
V/FA: Inactivity, disconnecting from the service
```

no actual errors or anything to debug it

**Comment by martinbonnin** [comment]
` onFailure(@NotNull Throwable t)` gives you a throwable that should contain the whole backstack. Try doing `Log.e("MYAPP", "exception", e);` to dump it (see https://stackoverflow.com/questions/4341363/android-print-full-exception-backtrace-to-log).

**Comment by dualcnhq** [comment]
@martinbonnin my code snippet looks like this:

```
newOrdersSubscription?.execute(object :
      ApolloSubscriptionCall.Callback<NewOrdersSubscription.Data> {
      override fun onFailure(e: ApolloException) {
        Log.d(TAG, "onFailure: ${e.localizedMessage}") // this one just returns Failed to parse server message
      }

      override fun onResponse(response: Response<NewOrdersSubscription.Data>) {
        Log.d(TAG, response.data().toString())
      }

      override fun onConnected() {
        Log.d(TAG, "onConnected: Connected to WS")
      }

      override fun onTerminated() {
        Log.d(TAG, "onTerminated: Disconnected from WS")
      }

      override fun onCompleted() {
        Log.d(TAG, "onFailure: Connection completed")
      }
    })
```

how can i override `@onFailure` ?

**Comment by martinbonnin** [comment]
Just change `Log.d(TAG, "onFailure: ${e.localizedMessage}")` to `Log.d(TAG, "onFailure", e)`. It should show your full backstack

**Comment by dualcnhq** [comment]
got it!

```
2019-11-18 17:22:36.315 26613-26727/com.mydomain.testapp D/InProgressFragment: onConnected: Connected to WS
2019-11-18 17:22:36.315 26613-26727/com.mydomain.testapp D/InProgressFragment: onConnected: Connected to WS
2019-11-18 17:22:37.186 26613-26727/com.mydomain.testapp E/InProgressFragment: onFailure: com.apollographql.apollo.internal.subscription.ApolloSubscriptionException: Failed to parse server message
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onOperationDataServerMessage(RealSubscriptionManager.java:321)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onOperationServerMessage(RealSubscriptionManager.java:234)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$3.run(RealSubscriptionManager.java:448)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalArgumentException: Can't map GraphQL type: uuid to: class java.lang.Object. Did you forget to add custom type adapter?
        at com.apollographql.apollo.response.ScalarTypeAdapters.adapterFor(ScalarTypeAdapters.java:35)
        at com.apollographql.apollo.internal.response.RealResponseReader.readCustomType(RealResponseReader.java:193)
        at com.mydomain.testapp.api.GetOrderListSubscription$Order$Mapper.map(GetOrderListSubscription.java:289)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper$1$1.read(GetOrderListSubscription.java:183)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper$1$1.read(GetOrderListSubscription.java:180)
        at com.apollographql.apollo.internal.response.RealResponseReader$ListItemReader.readObject(RealResponseReader.java:313)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper$1.read(GetOrderListSubscription.java:180)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper$1.read(GetOrderListSubscription.java:177)
        at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:168)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper.map(GetOrderListSubscription.java:177)
        at com.mydomain.testapp.api.GetOrderListSubscription$Data$Mapper.map(GetOrderListSubscription.java:172)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:56)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onOperationDataServerMessage(RealSubscriptionManager.java:317)
```

**Comment by martinbonnin** [comment]
You'll need to add a custom type adapter for uuid. See https://github.com/apollographql/apollo-android#custom-scalar-types

**Comment by dualcnhq** [comment]
is this correct:

i added this in `app/build.gradle`
```
apollo {
    customTypeMapping = [
            "uuid" : "java.lang.String"
    ]
}

```

```
val uuidCustomTypeAdapter = object : CustomTypeAdapter<String> {
      override fun decode(@NotNull value: CustomTypeValue<*>): String {
          return value.toString()
      }

      override fun encode(value: String): CustomTypeValue<*> {
         return CustomTypeValue.GraphQLString(value)
      }
}

apolloClient = ApolloClient.builder()
      .serverUrl(GRAPHQL_ENDPOINT)
      .okHttpClient(okHttpClient)
      .normalizedCache(normalizedCacheFactory, cacheKeyResolver)
      .addCustomTypeAdapter(CustomType.UUID, uuidCustomTypeAdapter)
      .subscriptionTransportFactory(
        WebSocketSubscriptionTransport.Factory(
          GRAPHQL_WEBSOCKET_ENDPOINT,
          okHttpClient
        )
      )
      .build()
```

**Comment by dualcnhq** [comment]
closing this issue now, thanks for the help
