### ISSUE TITLE
Gradle Plugin doesn't work with Gradle 6.x

### ISSUE THREAD

**Issue by kenyee** [apollographql/apollo-android#1827]
**Summary**
Trying to use the latest version of Android Studio 4.0 which requires Gradle 6.x with their latest plugin.  All our other plugins work except the Apollo GraphQL one :-(

The fix looks fairly straightforward...just use ObjectFactory.mapFactory instead of what ApolloExtension does.

**Description**
Stack trace from gradle
```
Caused by: org.gradle.api.InvalidUserCodeException: Please use the ObjectFactory.mapProperty() method to create a property of type Map<K, V>.
        at org.gradle.api.internal.model.DefaultObjectFactory.property(DefaultObjectFactory.java:157)
        at org.gradle.api.model.ObjectFactory$property.call(Unknown Source)
        at com.apollographql.apollo.gradle.ApolloExtension.<init>(ApolloExtension.groovy:49)
        at com.apollographql.apollo.gradle.ApolloExtension_Decorated.<init>(Unknown Source)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1858)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newIns
```

**Version**
We're using something prior to Apollo 1.2.2 (forked it because our backend only supports MD5 for the graphql query hash) 🤦‍♂

**Comment by digitalbuddha** [comment]
Could you try with 1.2.2 please

**Comment by martinbonnin** [comment]
@kenyee can you try the incubating plugin? Replace "com.apollographql.apollo:apollo-gradle-plugin" with "com.apollographql.apollo:apollo-gradle-plugin-incubating". 

More details there: https://github.com/apollographql/apollo-android/blob/460a7db8cfb9f8d4b37cc33dc95fc31b2ed5e7f2/doc/incubating-plugin.md#using-the-incubating-plugin

**Comment by kenyee** [comment]
turns out this is a bug in our ancient fork :-(

The actual code line is:
    customTypeMapping = project.objects.property(Map.class)

Which this repo has already fixed to be:
   customTypeMapping = project.objects.mapProperty(String.class, String.class)

Looks like you're good...sorry about the false alarm....

**Comment by luismz95** [comment]
apply plugin: 'com.apollographql.android' 
i removed this and works for me,
