### ISSUE TITLE
Add toJson method for writing response objects to strings

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#1881]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a "mock" mode to my app where the server logic is implemented in-app.  I've got a mock okhttp Client built but I would like to be able to automatically turn the generated response objects into json strings to put in the response body.  I can write my own `ResponseWriter` but that feels janky and unnecessary.

**Describe the solution you'd like**
```
fun ResponseWriter.toJson(): String?
```

Let me know if this is something you'd be amenable to and I can make a PR.  Or if it's already possible and I'm just not seeing the API.

**Comment by sav007** [comment]
Have you tried: `com.apollographql.apollo.response.OperationJsonWriter`
Sample: https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/IntegrationTest.java#L272-L286

But I think we can think of how to make this API better, one option is to have new API added to  `com.apollographql.apollo.api.Operation#marshal(ScalarTypeAdapters scalarTypeAdapters):String`.

**Comment by edenman** [comment]
That totally works, thanks!  I would definitely be in favor of a cleaner API though :)

**Comment by edenman** [comment]
this totally doesn't work, on further testing....I get this exception:
```
java.lang.IllegalStateException: Nesting problem.
        at com.apollographql.apollo.internal.json.JsonUtf8Writer.beforeValue(JsonUtf8Writer.java:370)
        at com.apollographql.apollo.internal.json.JsonUtf8Writer.nullValue(JsonUtf8Writer.java:182)
        at com.apollographql.apollo.response.OperationJsonWriter$JsonResponseResolver.didResolveNull(OperationJsonWriter.java:121)
        at com.apollographql.apollo.internal.response.RealResponseWriter.resolveObjectFields(RealResponseWriter.java:165)
        at com.apollographql.apollo.internal.response.RealResponseWriter.resolveFields(RealResponseWriter.java:138)
        at com.apollographql.apollo.internal.response.RealResponseWriter.resolveObjectFields(RealResponseWriter.java:167)
        at com.apollographql.apollo.internal.response.RealResponseWriter.resolveFields(RealResponseWriter.java:138)
        at com.apollographql.apollo.internal.response.RealResponseWriter.resolveFields(RealResponseWriter.java:86)
        at com.apollographql.apollo.response.OperationJsonWriter.write(OperationJsonWriter.java:38)
        at com.envoy.app.mockmode.CallMockServerInterceptor.toJson(MockApolloApi.kt:80)```
