### ISSUE TITLE
Add more detail to CacheFieldValueResolver NPE message?

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#1952]
**Is your feature request related to a problem? Please describe.**
I've had a few issues in my app related to the Cache being misconfigured.  The resulting crash is usually something like this:
```
Caused by java.lang.NullPointerException: Missing value: formattedName
       at com.apollographql.apollo.internal.field.CacheFieldValueResolver.fieldValue(CacheFieldValueResolver.java:101)
       at com.apollographql.apollo.internal.field.CacheFieldValueResolver.valueFor(CacheFieldValueResolver.java:43)
       at com.apollographql.apollo.internal.field.CacheFieldValueResolver.valueFor(CacheFieldValueResolver.java:16)
       at com.apollographql.apollo.internal.response.RealResponseReader.readString(RealResponseReader.java:44)
       at queries.FooQuery$Foo$Companion.invoke(FooQuery.java:349)
```

**Describe the solution you'd like**
I'd love to get more information about what other fields _are_ on the Record so I can get an idea of what the cache issue is.  For instance, if I'm getting the above stacktrace and I know `Foo` only has `id` and `formattedName` fields, but there's a `Taco` object with `id` and `bar` fields, knowing that the Record is actually a `Taco` would be super-helpful.  

I'm flexible on what this actually looks like.  Could just add `Record.toString()` to the message, but that could be a huge amount of output?  Hell, even just the `__typename` value and `ID` value would be helpful.

**Comment by edenman** [comment]
Or: make this a typed Exception and just put the whole `Record` on there, so I can try/catch and introspect it myself?
