### ISSUE TITLE
[Version 1.3] Regression causes ApolloParseException on valid GQL response

### ISSUE THREAD

**Issue by andrewmunn** [apollographql/apollo-android#1968]
**Summary**
After upgrading to Apollo 1.3 and using Kotlin code generation, we've started hitting the following a `ApolloParseException` on a GQL response that worked fine with Apollo 1.2.

**Description**
We get the following stack trace during parse time:
```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:146)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:216)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: pageFragment must not be null
    at com.nextdoor.apollo.fragment.PageAuthorFragment$Page$Fragments$Companion.invoke(PageAuthorFragment.kt:141)
    at com.nextdoor.apollo.fragment.PageAuthorFragment$Page$Companion.invoke(PageAuthorFragment.kt:114)
    at com.nextdoor.apollo.fragment.PageAuthorFragment$Companion$invoke$page$1.read(PageAuthorFragment.kt:58)
    at com.nextdoor.apollo.fragment.PageAuthorFragment$Companion$invoke$page$1.read(PageAuthorFragment.kt:35)
    at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:145)
    at com.nextdoor.apollo.fragment.PageAuthorFragment$Companion.invoke(PageAuthorFragment.kt:57)
    at com.nextdoor.apollo.fragment.AuthorFragment$Fragments$Companion$invoke$pageAuthorFragment$1.read(AuthorFragment.kt:89)
    at com.nextdoor.apollo.fragment.AuthorFragment$Fragments$Companion$invoke$pageAuthorFragment$1.read(AuthorFragment.kt:65)
    at com.apollographql.apollo.internal.response.RealResponseReader.readFragment(RealResponseReader.java:231)
    at com.nextdoor.apollo.fragment.AuthorFragment$Fragments$Companion.invoke(AuthorFragment.kt:87)
    at com.nextdoor.apollo.fragment.AuthorFragment$Companion.invoke(AuthorFragment.kt:44)
```
At first I thought our server was returning invalid GQL, but I inspected the response JSON and all seems right. Here is the GQL Fragments:

```
fragment AuthorFragment on Author {
    ...PageAuthorFragment
    ...AuthorCommonFragment
}

fragment AuthorCommonFragment on Author {
    authorType
    url
    avatar {
        ...ImageFragment
    }
    badges {
        ...BadgesFragment
    }
    displayName
}

fragment PageAuthorFragment on PageAuthor {
    ...AuthorCommonFragment
    supporterCount
    page {
        ...PageFragment
    }
}
fragment PageFragment on Page {
    legacyId
    name
}
```
Here is the seemingly valid HTTP response:
```
"author": {
    "__typename": "PageAuthor",
    "authorType": "PAGES",
    "url": "/pages/company_name/",
    "avatar": {
        "__typename": "Image",
        "url": "someurl.png",
        "widthPx": null,
        "heightPx": null
    },
    "badges": {
        "__typename": "Badges",
        "foundingMember": false,
        "lead": false,
        "inviteCount": null,
        "agency": false
    },
    "displayName": "COMPANY",
    "supporterCount": 0,
    "page": {
        "__typename": "MinimalPage",
        "legacyId": "3827392",
        "name": "COMPANY"
    }
}
```

Here is the generated `PageAuthorFragment.kt` in 1.2
```
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.nextdoor.apollo.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.ResponseFieldMarshaller
import com.apollographql.apollo.api.ResponseReader
import kotlin.Array
import kotlin.Int
import kotlin.String
import kotlin.Suppress

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class PageAuthorFragment(
  val __typename: String,
  /**
   * number of supporters on a business page author
   */
  val supporterCount: Int?,
  val page: Page,
  val fragments: Fragments
) : GraphqlFragment {
  override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
    it.writeString(RESPONSE_FIELDS[0], __typename)
    it.writeInt(RESPONSE_FIELDS[1], supporterCount)
    it.writeObject(RESPONSE_FIELDS[2], page.marshaller())
    fragments.marshaller().marshal(it)
  }

  companion object {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
        ResponseField.forString("__typename", "__typename", null, false, null),
        ResponseField.forInt("supporterCount", "supporterCount", null, true, null),
        ResponseField.forObject("page", "page", null, false, null),
        ResponseField.forString("__typename", "__typename", null, false, null)
        )

    val FRAGMENT_DEFINITION: String = """
        |fragment PageAuthorFragment on PageAuthor {
        |  __typename
        |  ...AuthorCommonFragment
        |  supporterCount
        |  page {
        |    __typename
        |    ...PageFragment
        |  }
        |}
        """.trimMargin()

    val POSSIBLE_TYPES: Array<String> = arrayOf("PageAuthor")

    operator fun invoke(reader: ResponseReader): PageAuthorFragment {
      val __typename = reader.readString(RESPONSE_FIELDS[0])
      val supporterCount = reader.readInt(RESPONSE_FIELDS[1])
      val page = reader.readObject<Page>(RESPONSE_FIELDS[2]) { reader ->
        Page(reader)
      }

      val fragments = reader.readConditional(RESPONSE_FIELDS[3]) { conditionalType, reader ->
        val authorCommonFragment = if
            (AuthorCommonFragment.POSSIBLE_TYPES.contains(conditionalType))
            AuthorCommonFragment(reader) else null
        Fragments(
          authorCommonFragment = authorCommonFragment
        )
      }

      return PageAuthorFragment(
        __typename = __typename,
        supporterCount = supporterCount,
        page = page,
        fragments = fragments
      )
    }
  }

  data class Fragments(
    val authorCommonFragment: AuthorCommonFragment?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      authorCommonFragment?.marshaller()?.marshal(it)
    }
  }

  data class Page(
    val __typename: String,
    val fragments: Fragments
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      it.writeString(RESPONSE_FIELDS[0], __typename)
      fragments.marshaller().marshal(it)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forString("__typename", "__typename", null, false, null)
          )

      operator fun invoke(reader: ResponseReader): Page {
        val __typename = reader.readString(RESPONSE_FIELDS[0])
        val fragments = reader.readConditional(RESPONSE_FIELDS[1]) { conditionalType, reader ->
          val pageFragment = PageFragment(reader)
          Fragments(
            pageFragment = pageFragment
          )
        }

        return Page(
          __typename = __typename,
          fragments = fragments
        )
      }
    }

    data class Fragments(
      val pageFragment: PageFragment
    ) {
      fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
        pageFragment.marshaller().marshal(it)
      }
    }
  }
}

```
Here is it is in 1.3:
```
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.nextdoor.apollo.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.ResponseFieldMarshaller
import com.apollographql.apollo.api.ResponseReader
import kotlin.Array
import kotlin.Int
import kotlin.String
import kotlin.Suppress

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class PageAuthorFragment(
  val __typename: String,
  /**
   * number of supporters on a business page author
   */
  val supporterCount: Int?,
  val page: Page,
  val fragments: Fragments
) : GraphqlFragment {
  override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
    it.writeString(RESPONSE_FIELDS[0], __typename)
    it.writeInt(RESPONSE_FIELDS[1], supporterCount)
    it.writeObject(RESPONSE_FIELDS[2], page.marshaller())
    fragments.marshaller().marshal(it)
  }

  companion object {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
        ResponseField.forString("__typename", "__typename", null, false, null),
        ResponseField.forInt("supporterCount", "supporterCount", null, true, null),
        ResponseField.forObject("page", "page", null, false, null)
        )

    val FRAGMENT_DEFINITION: String = """
        |fragment PageAuthorFragment on PageAuthor {
        |  __typename
        |  ...AuthorCommonFragment
        |  supporterCount
        |  page {
        |    __typename
        |    ...PageFragment
        |  }
        |}
        """.trimMargin()

    operator fun invoke(reader: ResponseReader): PageAuthorFragment {
      val __typename = reader.readString(RESPONSE_FIELDS[0])
      val supporterCount = reader.readInt(RESPONSE_FIELDS[1])
      val page = reader.readObject<Page>(RESPONSE_FIELDS[2]) { reader ->
        Page(reader)
      }

      val fragments = Fragments(reader)
      return PageAuthorFragment(
        __typename = __typename,
        supporterCount = supporterCount,
        page = page,
        fragments = fragments
      )
    }
  }

  data class Fragments(
    val authorCommonFragment: AuthorCommonFragment?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      it.writeFragment(authorCommonFragment?.marshaller())
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forFragment("__typename", "__typename", listOf(
            ResponseField.Condition.typeCondition(arrayOf("CityAgencyAuthor", "UserAuthor",
                "PageAuthor", "SystemAuthor"))
          ))
          )

      operator fun invoke(reader: ResponseReader): Fragments {
        val authorCommonFragment = reader.readFragment<AuthorCommonFragment>(RESPONSE_FIELDS[0]) {
            reader ->
          AuthorCommonFragment(reader)
        }
        return Fragments(
          authorCommonFragment = authorCommonFragment
        )
      }
    }
  }

  data class Page(
    val __typename: String,
    val fragments: Fragments
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      it.writeString(RESPONSE_FIELDS[0], __typename)
      fragments.marshaller().marshal(it)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null)
          )

      operator fun invoke(reader: ResponseReader): Page {
        val __typename = reader.readString(RESPONSE_FIELDS[0])
        val fragments = Fragments(reader)
        return Page(
          __typename = __typename,
          fragments = fragments
        )
      }
    }

    data class Fragments(
      val pageFragment: PageFragment
    ) {
      fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
        it.writeFragment(pageFragment.marshaller())
      }

      companion object {
        private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
            ResponseField.forFragment("__typename", "__typename", listOf(
              ResponseField.Condition.typeCondition(arrayOf("MunicipalPage", "MinimalPage"))
            ))
            )

        operator fun invoke(reader: ResponseReader): Fragments {
          val pageFragment = reader.readFragment<PageFragment>(RESPONSE_FIELDS[0]) { reader ->
            PageFragment(reader)
          }
          return Fragments(
            pageFragment = pageFragment
          )
        }
      }
    }
  }
}

```

**Version**
Provide a version of library on which the problem occurred.
1.3. We've downgraded to 1.2.1 in the meantime, which does not have this bug.

**Comment by edenman** [comment]
worth checking what the codegen has for `RESPONSE_FIELDS`.  I ran into a mock mode issue where the `__typename` wasn't correct and the Kotlin codegen treats that as an error.  Maybe `MinimalPage` isn't the expected value in `ResponseField.Condition.typeCondition`?

**Comment by tasomaniac** [comment]
I think it would also be nice to provide the generated `PageAuthorFragment.kt`

**Comment by andrewmunn** [comment]
@tasomaniac updated the bug with the code from 1.2 and 1.3

**Comment by sav007** [comment]
Super weird , I can't reproduce it. I took your response and generated models for 1.3 version and it works.

**Comment by andrewmunn** [comment]
can no longer reproduce 1.3.2
