### ISSUE TITLE
can't use livedata with apollo android 

### ISSUE THREAD

**Issue by moun3iim** [apollographql/apollo-android#2027]
I had a problem when I've tried to use livedata with apollo android, this's my code
```
class SignInViewModel : ViewModel() {

    enum class AuthenticationState {
        UNAUTHENTICATED,
        AUTHENTICATED  ,
        INVALID_AUTHENTICATION
    }

    val authenticationState = MutableLiveData<AuthenticationState>()

    init {
        authenticationState.value = AuthenticationState.UNAUTHENTICATED
    }

    fun signIn(email: String, password: String) {
        val signInMutation = SignInMutation(email, password)

        getClient().mutate(signInMutation).enqueue(object : ApolloCall.Callback<SignInMutation.Data>() {
            override fun onResponse(response: Response<SignInMutation.Data>) {
                val token = response.data()?.signIn?.token!!
                Log.i("token", token)
                authenticationState.value = AuthenticationState.AUTHENTICATED

            }

            override fun onFailure(e: ApolloException) {
                Log.i("signIn", e.message, e)
            }

        })
    }
}
```
and this's the error
```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.example.a2cpi_project_app_kotlin, PID: 19554
    kotlin.KotlinNullPointerException
        at com.example.a2cpi_project_app_kotlin.start.signIn.SignInViewModel$signIn$1.onResponse(SignInViewModel.kt:35)
        at com.apollographql.apollo.internal.RealApolloCall$1.onResponse(RealApolloCall.java:243)
        at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:85)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:54)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:146)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```
when I remove `authenticationState.value = AuthenticationState.AUTHENTICATED` it work fine

**Comment by mrctrifork** [comment]
When you enqueue a callback, that callback is dispatched from a background thread. Be careful since you can only `LiveData#setValue` from the MainThread and you are not respecting that with kotlin's the syntactic sugar for the assignation.

If you'd like to update the value from a background thread you should use the method `LiveData#postValue` instead.

**Comment by moun3iim** [comment]
> When you enqueue a callback, that callback is dispatched from a background thread. Be careful since you can only `LiveData#setValue` from the MainThread and you are not respecting that with kotlin's the syntactic sugar for the assignation.
> 
> If you'd like to update the value from a background thread you should use the method `LiveData#postValue` instead.

Thanks, it solved the problem
