### ISSUE TITLE
Make Code Gen work on windows

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#209]
Windows and npm are not playing well together.  What I think is happening:
Gradle plugin installs its own node without root privileges, when it tries to run the node task we get a sad permission error.  This is the command that is being run:
```"install" "apollo-codegen@0.10.5" "--save" "--save-exact"```

and the glorious errors that this results in :-)

```
10:14:27.360 [ERROR] [system.err] npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Home\\Desktop\\apollo-android-master\\apollo-android-master\\apollo-sample\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe" "C:\\Users\\Home\\Desktop\\apollo-android-master\\apollo-android-master\\apollo-sample\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "apollo-codegen@0.10.5" "--save" "--save-exact"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\apollo-codegen
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\apollo-codegen' -> 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\.apollo-codegen.DELETE'
npm ERR!     at moveAway (C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\apollo-codegen' -> 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\.apollo-codegen.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\apollo-codegen' -> 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\.apollo-codegen.DELETE'
npm ERR!     at moveAway (C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\apollo-codegen' -> 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\node_modules\.apollo-codegen.DELETE'
npm ERR!     at Error (native) parent: 'apollo-android' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\npm-debug.log

10:14:27.431 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
10:14:27.431 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with exit value -4048 (state: FAILED)
10:14:27.432 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
10:14:27.432 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':apollo-sample:installApolloCodegen'
10:14:27.432 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :apollo-sample:installApolloCodegen FAILED
10:14:27.432 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 371: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
10:14:27.433 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :apollo-sample:installApolloCodegen (Thread[Daemon worker Thread 6,5,main]) completed. Took 7.407 secs.
10:14:27.433 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.19 completed (0 in use)
10:14:27.433 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 6,5,main]] finished, busy: 7.714 secs, idle: 0.006 secs
10:14:27.433 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 371: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent

10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':apollo-sample:installApolloCodegen'.
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value -4048
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:14:27.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apollo-sample:installApolloCodegen'.
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
10:14:27.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
10:14:27.436 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Home\Desktop\apollo-android-master\apollo-android-master\apollo-sample\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value -4048
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:176)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:951)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:947)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.Project$exec$5.call(Unknown Source)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:36)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.NodeExecRunner.doExecute(NodeExecRunner.groovy:44)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:66)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.npm.NpmExecRunner.doExecute(NpmExecRunner.groovy:49)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:66)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.npm.NpmTask.exec(NpmTask.groovy:90)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 78 more
10:14:27.437 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
```

**Comment by sav007** [comment]
@marwanad could you pls help us with this

**Comment by marwanad** [comment]
@sav007 yeah, will take a look.

**Comment by imthehell** [comment]
I also have this error. Do you have a workaround?

**Comment by marwanad** [comment]
@imthehell This should be fixed with latest snapshot. Are you on the latest master build?

**Comment by migos** [comment]
I got the same error. Tried to use the snapshot but got the following error:

**Comment by StephenBrough** [comment]
I just got this error. Fixed it by updating the `gradle-node-plugin` dependency from `1.0.0` to `1.2.0`
