### ISSUE TITLE
When an object of a union type receives an unknown type, ApolloParseException is thrown

### ISSUE THREAD

**Issue by francescocervone** [apollographql/apollo-android#2097]
**Summary**
I expect that unions behave similar to enum types, that is, mapping unknown new types into an `Unknown` generated type.

**Description**
Let's say you have a union defined as:
```
union Action = Action1 | Action2
```
We deploy our app with a schema that support these two action.
At some point, the backend adds `Action3` to the union `Action`.
```
union Action = Action1 | Action2 | Action3
```
I expect that older apps don't break if `Action3` is received. If that's the intended behavior, it would mean that every time the backend adds a new type to a union we need to deprecate all older apps and release a new app that supports the new schema.

We always map unions into fragments so we don't know actually if this issue happens only with fragments.
When the fragment gets instantiated:
- With the Kotlin code generator an `IllegalStateException` wrapped into an `ApolloParseException` is thrown
- With the Java code generator a `NullPointerException` wrapped into an `ApolloParseException` is thrown

Currently, looks like the iOS generator handles this use case as expected. Our iOS app doesn't have the same issue.

**Version**
1.3.3 (tested with both Kotlin and Java code generators).

P.S.
I'm not sure this is a bug or an intended behavior. It looked more like a bug, so I opened this issue as a bug.

### Edit
I've tested the use case without using fragments. When not using fragments for unions, everything works as expected: if client app receives an unsupported type from the backend, no `ApolloParseException` is thrown. Quoting my previous example, the unknown action `Action3` is mapped into an object like this:
```
Action(
  asAction1 = null,
  asAction2 = null
)
```

**Comment by sav007** [comment]
Could you please share your sample of query that causes this issue?

**Comment by sav007** [comment]
Also could you please provide a full stack of the exception

**Comment by francescocervone** [comment]
@sav007 

Imagine that the schema of the compiled app has:
```
union LoginResponse = LoginSuccess
```
At some point, the backend adds the `LoginFailure` type, and the updated schema is:
```
union LoginResponse = LoginSuccess | LoginFailure
```
Even if the schema has been updated by the backend, out there we still have apps distributed with the old schema, withtout `LoginFailure`.

This is a sample mutation:
```graphql
mutation LoginMutation($username: String!, $password: String!) {
    login(username: $username, password: $password) {
        ...LoginResponseFragment
    }
}

fragment LoginResponseFragment on LoginResponse {
    ... on LoginSuccess {
        token
    }
}
```

This is the stacktrace if backend returns a `LoginFailure`:
```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:100)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:52)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:146)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: loginResponseFragment must not be null
        at it.prima.networking.model.LoginMutation$Login$Fragments$Companion.invoke(LoginMutation.kt:112)
        at it.prima.networking.model.LoginMutation$Login$Companion.invoke(LoginMutation.kt:84)
        at it.prima.networking.model.LoginMutation$Data$Companion$invoke$1$login$1.read(LoginMutation.kt:139)
        at it.prima.networking.model.LoginMutation$Data$Companion$invoke$1$login$1.read(LoginMutation.kt:126)
        at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:145)
        at it.prima.networking.model.LoginMutation$Data$Companion.invoke(LoginMutation.kt:138)
        at it.prima.networking.model.LoginMutation$responseFieldMapper$1.map(LoginMutation.kt:57)
        at it.prima.networking.model.LoginMutation$responseFieldMapper$1.map(LoginMutation.kt:34)
        at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:98)
        at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:93)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:86)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:52) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:146) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

The exception is thrown in the Apollo generated code (see image below, line 112)

<img width="748" alt="Schermata 2020-03-28 alle 10 27 42" src="https://user-images.githubusercontent.com/6197796/77819914-d2ce2f80-70de-11ea-95d7-640f4be41284.png">

The issue is caused by the `typeCondition` at line 102 that prevents the fragment to be created.

This does not happen if I use an inline fragment.

Hope this helps.
