### ISSUE TITLE
Exception in ScalarTypeAdapters

### ISSUE THREAD

**Issue by asadi110** [apollographql/apollo-android#2301]
**Summary**
```
Fatal Exception: java.lang.AbstractMethodError
abstract method "okio.ByteString i.d.a.g.l.a(boolean, boolean, com.apollographql.apollo.api.ScalarTypeAdapters)"
com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpPostRequestBody
```

**Description**
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "okio.ByteString i.d.a.g.l.a(boolean, boolean, com.apollographql.apollo.api.ScalarTypeAdapters)"
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpPostRequestBody(ApolloServerInterceptor.java:213)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpPostCall(ApolloServerInterceptor.java:164)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.executeHttpCall(ApolloServerInterceptor.java:111)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run(ApolloServerInterceptor.java:85)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Version**
2.1.0

**Comment by martinbonnin** [comment]
Thanks for the bug report. A few questions to try to pinpoint the issue:

* Is this a regression? E.g. was the same code working on a previous version of apollo-android?
* Does it also happen if you disable proguard/r8?
* Are you generating Java or Kotlin models?
* Can you share a generated model ? It should contain code like:

```
  override fun composeRequestBody(
    autoPersistQueries: Boolean,
    withQueryDocument: Boolean,
    scalarTypeAdapters: ScalarTypeAdapters
  ): ByteString = OperationRequestBodyComposer.compose(
    operation = this,
    autoPersistQueries = autoPersistQueries,
    withQueryDocument = withQueryDocument,
    scalarTypeAdapters = scalarTypeAdapters
  )
```

**Comment by martinbonnin** [comment]
Closing due to inactivity
