### ISSUE TITLE
Failed resolution of: Ljava/util/Base64 when implementing AppSyncOperationMessageSerializer

### ISSUE THREAD

**Issue by kkogut95** [apollographql/apollo-android#2857]
**Summary**
When trying to implement the `AppSyncOperationMessageSerializer` app is crashing because of failed resolution of `java.util.Base64`

**Version**
com.apollographql.apollo -> `2.5.2`
com.apollographql.apollo:apollo-runtime -> `2.5.2`

**Description**
I'm using Android 5.1 device and it's crashing when creating `AppSyncOperationMessageSerializer`. I think that in order to fix that `java.util.Base64` should be changed to `android.util.Base64`?

    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.apollographql.apollo.subscription.AppSyncOperationMessageSerializer$Companion.base64Encode(AppSyncOperationMessageSerializer.kt:115)
        at com.apollographql.apollo.subscription.AppSyncOperationMessageSerializer$Companion.buildWebSocketUrl(AppSyncOperationMessageSerializer.kt:100)
        at com.apollographql.apollo.subscription.AppSyncOperationMessageSerializer$Companion.buildWebSocketUrl$default(AppSyncOperationMessageSerializer.kt:88)

**Comment by martinbonnin** [comment]
That's interesting, I would expect Android to also have `android.util.Base64`: https://developer.android.com/reference/java/util/Base64. What kind on device are you testing on?

**Comment by martinbonnin** [comment]
> `Added in API level 26` 

Alright so I guess that explains it. Also ping @ansmam, we might want to do thing a little bit different there.
