### ISSUE TITLE
 java.lang.IllegalArgumentException: networkResponse.priorResponse != null

### ISSUE THREAD

**Issue by halysongoncalves** [apollographql/apollo-android#2998]
**Summary**

```
    java.lang.IllegalArgumentException: networkResponse.priorResponse != null
        at okhttp3.Response$Builder.checkSupportResponse(Response.kt:408)
        at okhttp3.Response$Builder.networkResponse(Response.kt:394)
        at com.apollographql.apollo.cache.http.HttpCacheInterceptor.networkFirst(HttpCacheInterceptor.java:111)
        at com.apollographql.apollo.cache.http.HttpCacheInterceptor.intercept(HttpCacheInterceptor.java:51)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.globo.jarvis.JarvisClient$providerHeaderInterceptor$1.intercept(Unknown Source:219)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Version**
2.4.4

**Description**
When I add the following cache rules and I get an error from the server (408, 500), the crash happens

**Comment by halysongoncalves** [comment]
@martinbonnin I'm from the Globoplay team

**Comment by martinbonnin** [comment]
Hi @halysongoncalves, can you share your cache rules ?

**Comment by halysongoncalves** [comment]
internal fun buildApolloClient() = ApolloClient
        .builder()
        .serverUrl(settings.environment())
        .httpCache(
            ApolloHttpCache(
                DiskLruHttpCacheStore(
                    File(
                        settings.application().cacheDir,
                        CACHE_APOLLO
                    ), CACHE_SIZE
                )
            )
        )
        .defaultHttpCachePolicy(HttpCachePolicy.NETWORK_FIRST)
        .useHttpGetMethodForQueries(true)
        .useHttpGetMethodForPersistedQueries(true)
        .enableAutoPersistedQueries(true)
        .defaultHttpCachePolicy(HttpCachePolicy.NETWORK_FIRST)
        .addCustomTypeAdapter(CustomType.DATE, DateTypeAdapter())
       
        .okHttpClient(
            OkHttpClient
                .Builder()
                .addInterceptor(providerInterceptorLogging(settings.enableLog()))
                .addInterceptor(providerHeaderInterceptor())
                .connectTimeout(settings.timeout(), TimeUnit.SECONDS)
                .readTimeout(settings.timeout(), TimeUnit.SECONDS)
                .writeTimeout(settings.timeout(), TimeUnit.SECONDS)
                .build()
        )
        .build()

**Comment by martinbonnin** [comment]
Thanks ! I'm suspecting something with the logging interceptor. The logging interceptor somehow reads the whole body and this doesn't seem to play super nice with the HTTP cache interceptor (see https://github.com/apollographql/apollo-android/issues/2968). Can you try without the logging interceptor?

**Comment by halysongoncalves** [comment]
I will do the test

**Comment by halysongoncalves** [comment]
I removed all the interceptors registered in okhttp, but the problem still persists:

 Process: com.globo.globotv, PID: 6185
    java.lang.IllegalArgumentException: networkResponse.priorResponse != null
        at okhttp3.Response$Builder.checkSupportResponse(Response.kt:408)
        at okhttp3.Response$Builder.networkResponse(Response.kt:394)
        at com.apollographql.apollo.cache.http.HttpCacheInterceptor.networkFirst(HttpCacheInterceptor.java:111)
        at com.apollographql.apollo.cache.http.HttpCacheInterceptor.intercept(HttpCacheInterceptor.java:51)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by halysongoncalves** [comment]
![Captura de Tela 2021-03-12 às 18 52 15](https://user-images.githubusercontent.com/5872045/111002382-19568180-8364-11eb-80ed-bd6857c6f24b.png)

**Comment by martinbonnin** [comment]
Thanks for trying that! Looks like it's something else then, maybe some interaction between the persisted queries and the cache. It's getting pretty late here but I'll try to reproduce first thing on Monday!

**Comment by halysongoncalves** [comment]
Thanks

**Comment by halysongoncalves** [comment]
@martinbonnin any news?

**Comment by martinbonnin** [comment]
Arg very sorry ! Look like I forgot to hit enter this morning 🤦 

I haven't been able to reproduce unfortunately so it looks like there's something more to the story. I made a small reproducer there: https://github.com/martinbonnin/apollo-android-samples/tree/main/apq-and-http-cache

Any chance you can see a difference with your setup and/or try to make it fail?

**Comment by halysongoncalves** [comment]
Hey @martinbonnin, sorry for the delay!

I am using the following very similar settings:


<img width="651" alt="Captura de Tela 2021-03-18 às 16 38 32" src="https://user-images.githubusercontent.com/5872045/111686896-688b2f00-8808-11eb-8ef4-66af9120b2fc.png">
<img width="711" alt="Captura de Tela 2021-03-18 às 16 38 43" src="https://user-images.githubusercontent.com/5872045/111686908-6c1eb600-8808-11eb-952a-c9fd7ca0f07b.png">


To simulate server error, I'm using charles proxy.

I ended up checking that when we force a 500 error, the cache works correctly and I get the answer.

<img width="460" alt="Captura de Tela 2021-03-18 às 16 40 43" src="https://user-images.githubusercontent.com/5872045/111687273-d9cae200-8808-11eb-99ae-7d19267d1b16.png">

However, if I force return 408 (time out), the app receives the crash!

<img width="431" alt="Captura de Tela 2021-03-18 às 16 43 16" src="https://user-images.githubusercontent.com/5872045/111687455-0da60780-8809-11eb-890e-43af1004f124.png">
<img width="807" alt="Captura de Tela 2021-03-18 às 16 43 25" src="https://user-images.githubusercontent.com/5872045/111687461-0ed73480-8809-11eb-8e3a-bb10079ba1fd.png">


I believe it is related to the http status code 408, only with it does the crash happen!

**Comment by halysongoncalves** [comment]
And when I remove all intercepts the crash is evident in the HttpCacheInterceptor class in the networkFirst method

<img width="826" alt="Captura de Tela 2021-03-18 às 16 53 12" src="https://user-images.githubusercontent.com/5872045/111689236-8a85b100-880a-11eb-83d5-2c1fe53c66b7.png">

**Comment by martinbonnin** [comment]
Thanks ! That's an interesting scenario. Today I learnt about HTTP 208 and automatic retries ! Pull request there: https://github.com/apollographql/apollo-android/pull/3010/files

**Comment by halysongoncalves** [comment]
Awesome and thanks for the help!

**Comment by martinbonnin** [comment]
2.5.5 is released with the fix, let me know how that goes!

**Comment by halysongoncalves** [comment]
@martinbonnin Everything working perfectly, thanks!
