### ISSUE TITLE
NullPointerException when you are trying cancel subscription ver 3.0.0-dev5

### ISSUE THREAD

**Issue by SergeyMilevskiy** [apollographql/apollo-android#3005]
**_NullPointerException_**
Android 11

**3.0.0-dev5**

**Description**
```
java.lang.NullPointerException
        at com.apollographql.apollo3.internal.subscription.RealSubscriptionManager.removeSubscriptionById(RealSubscriptionManager.kt:370)
        at com.apollographql.apollo3.internal.subscription.RealSubscriptionManager.onCompleteServerMessage(RealSubscriptionManager.kt:354)
        at com.apollographql.apollo3.internal.subscription.RealSubscriptionManager.onOperationServerMessage(RealSubscriptionManager.kt:208)
        at com.apollographql.apollo3.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$onMessage$1.run(RealSubscriptionManager.kt:410)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by martinbonnin** [comment]
Woohoo, thanks for the very first bug report on `dev-3.x` 🎉  🍾 ! Will look into this!

Also heads up that `-dev` releases are for developer previews so it's fine to look into what's happening and file bugs but bugs/breaking changes are expected. We'll change to `-alpha` when things stabilize a bit and drop the `-alpha` qualifier when API is stable.

**Comment by SergeyMilewski** [comment]
Ok, I see, thank you for your feedback, actually, for unsubscribing, I use currently this method => apolloClient.subscriptionManager.stop() it stops and disconnects the client.

**Comment by SergeyMilevskiy** [comment]
Ok, I see, thank you for your feedback, actually, for unsubscribing, I use currently this method => apolloClient.subscriptionManager.stop() it stops and disconnects the client.

**Comment by martinbonnin** [comment]
Is there a reason you're not using the stable [2.5.4](https://github.com/apollographql/apollo-android/releases/tag/v2.5.4) version?

**Comment by SergeyMilevskiy** [comment]
The problem with subscriptions, workaround from the GitHub doesn't work for me. only with 3.0.0
`
val connectionParams = mapOf(AUTH_TOKEN to token)
subscriptionConnectionParams(SubscriptionConnectionParams(connectionParams))
`

**Comment by martinbonnin** [comment]
I'm confused. Is there something in `2.5.4` that doesn't work and works in `3.0.0-dev5` ? Can you point to the original `2.5.4` issue? We might want to fix it there since it's the stable branch

**Comment by martinbonnin** [comment]
@SergeyMilevskiy Since 3.x is moving fast, I'm going to close this one. Let me know if you want me to reopen it.
