### ISSUE TITLE
How to create a custom mapper for an scalar attribute in building time?

### ISSUE THREAD

**Issue by quim3ra** [apollographql/apollo-android#3105]
Hi,

We are having issues with the auto-generation of classes when using this graphQL schema and query:

GraphQL schema: https://github.com/braintree/graphql-api/blob/master/schema.graphql

query:

```
query TransactionSearchInput($input: TransactionSearchInput!) {
    search {
        transactions(input: $input) {
            pageInfo {
                hasNextPage
                startCursor
                endCursor
            },
            edges {
                node {
                    id
                    createdAt
                    orderId
                    status
                    amount {
                        value
                        currencyIsoCode
                    }
                    tax {
                        taxAmount
                        taxExempt
                    }
                    customFields {
                        name
                        value
                    }
                }
            }
        }
    }
}
```

The problem is that whenever we execute `./gradlew build` we get this error:

```
TransactionSearchInputQuery.java:973: error: cannot find symbol
                        final Object.Mapper objectFieldMapper = new java.lang.Object.Mapper();
                                    ^
  symbol:   class Mapper
  location: class Object
1 error
```

I know we can create a custom mapper like:

```
apollo {
    customTypeMapping = [
            "Field": "java.lang.String"
    ]
}
```

Thing is that I don't know how to register a custom mapper and let gradle know how to pick it up in building time.

Any leads?

Thank you so much!

**Comment by martinbonnin** [comment]
Hi @cbelizone2y 👋 

I don't think you need a `customTypeMapping` there. `customTypeMapping` is for custom scalars and it doesn't look like `Field` is one of them.

Do you explicitely need java models ? Or can you try the Kotlin codegen in your build.gradle files?

```
// build.gradle
apollo {
  generateKotlinModels.set(true)
}
```

**Comment by cbelizone2y** [comment]
> Hi @cbelizone2y 👋 
> 
> 
> 
> I don't think you need a `customTypeMapping` there. `customTypeMapping` is for custom scalars and it doesn't look like `Field` is one of them.
> 
> 
> 
> Do you explicitely need java models ? Or can you try the Kotlin codegen in your build.gradle files?
> 
> 
> 
> ```
> 
> // build.gradle
> 
> apollo {
> 
>   generateKotlinModels.set(true)
> 
> }
> 
> ```
Sadly for me I need to stick to only use Java for this project. The field is Amount field described in the dsl file, you can check it, I believe they have made a mistake on how they're defined the schema, but I doubt they'll change it. Any other feasible solution to try to workaround this issue?

**Comment by martinbonnin** [comment]
Right 👍 . Then you can do something like this:

```
apollo {
    customTypeMapping = [
            "Amount": "java.lang.String"
    ]
}
```

That will map all `Amount` custom scalars to java `Strings`.

You can then register your adapter with [`ApolloClient.addCustomTypeAdapter`](https://www.apollographql.com/docs/android/essentials/custom-scalar-types/)

**Comment by cbelizone2y** [comment]
I have tried also that, I forgot to mention, that whenever I do so, and I created a logic like this one:

build.gradle

```
apollo {
    customTypeMapping = [
            "Amount": "java.lang.String"
    ]
}
```

Amount class:

```java
public class Amount {
    public String amount;
    public String value;
}

```

Code to retrieve all transactions that are settled in a service class:

```java
final CustomTypeAdapter<Amount> amountCustomTypeAdapter = new CustomTypeAdapter<>() {
			@Override
			public Amount decode(@NotNull final CustomTypeValue<?> customTypeValue) {
				return new Amount();
			}

			@Override
			public @NotNull CustomTypeValue<?> encode(final Amount amount) {
				return CustomTypeValue.fromRawValue(amount);
			}
		};

		final OkHttpClient httpClient = new OkHttpClient.Builder().addInterceptor(chain -> {
			Request original = chain.request();
			Request.Builder builder = original.newBuilder().method(original.method(), original.body());
			builder.addHeader("Authorization",
					"Basic XXXXXX");
			return chain.proceed(builder.build());
		}).build();

		final ApolloClient apolloClient = ApolloClient.builder()
				.serverUrl("https://graphqEndpoint.com/graphqll")
				.okHttpClient(httpClient)
				.addCustomTypeAdapter(CustomType.AMOUNT, amountCustomTypeAdapter)
				.build();

		final TransactionSearchInput input = TransactionSearchInput.builder()
				.status(SearchTransactionStatusInput.builder().in(List.of(PaymentStatus.SETTLED)).build()).build();

		apolloClient.query(new TransactionSearchQuery(input)).enqueue(new ApolloCall.Callback<>() {

			@Override
			public void onResponse(@NotNull final Response<TransactionSearchQuery.Data> response) {
				final TransactionSearchQuery.Data data = response.getData();
				data.search().transactions().edges().stream().peek(s -> log.info(s.node().id())); //Just for printing something
			}

			@Override
			public void onFailure(@NotNull final ApolloException e) {
				log.error(e.getMessage(), e); //In case something goes wrong
			}
		});

		return ResponseEntity.ok().build();
```

And this is the error I got while executing the query:

```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:104) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.4.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.4.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
	at com.apollographql.apollo.internal.response.RealResponseReader.readString(RealResponseReader.kt:29) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Node$Mapper.map(TransactionSearchQuery.java:991) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Edge$Mapper$1.read(TransactionSearchQuery.java:767) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Edge$Mapper$1.read(TransactionSearchQuery.java:764) ~[main/:na]
	at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.kt:118) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Edge$Mapper.map(TransactionSearchQuery.java:764) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Transactions$Mapper$2$1.read(TransactionSearchQuery.java:530) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Transactions$Mapper$2$1.read(TransactionSearchQuery.java:527) ~[main/:na]
	at com.apollographql.apollo.internal.response.RealResponseReader$ListItemReader.readObject(RealResponseReader.kt:274) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Transactions$Mapper$2.read(TransactionSearchQuery.java:527) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Transactions$Mapper$2.read(TransactionSearchQuery.java:524) ~[main/:na]
	at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.kt:142) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Transactions$Mapper.map(TransactionSearchQuery.java:524) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Search$Mapper$1.read(TransactionSearchQuery.java:393) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Search$Mapper$1.read(TransactionSearchQuery.java:390) ~[main/:na]
	at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.kt:118) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Search$Mapper.map(TransactionSearchQuery.java:389) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Data$Mapper$1.read(TransactionSearchQuery.java:285) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Data$Mapper$1.read(TransactionSearchQuery.java:282) ~[main/:na]
	at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.kt:118) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Data$Mapper.map(TransactionSearchQuery.java:282) ~[main/:na]
	at com.paypal.braintree.transactions.TransactionSearchQuery$Data$Mapper.map(TransactionSearchQuery.java:276) ~[main/:na]
	at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:97) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:59) ~[apollo-api-jvm-2.5.6.jar:2.5.6]
	at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:92) ~[apollo-runtime-2.5.6.jar:2.5.6]
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87) ~[apollo-runtime-2.5.6.jar:2.5.6]
```

Notice that if I remove those 2 attributes from the query and I leave the `TransactionSearchQuery` like this:

```
query TransactionSearchQuery($input: TransactionSearchInput!) {
    search {
        transactions(input: $input) {
            pageInfo {
                hasNextPage
                startCursor
                endCursor
            },
            edges {
                node {
                    id
                    createdAt
                    orderId
                    status
                    customFields {
                        name
                        value
                    }
                }
            }
        }
    }
}
```

Everything works fine.

I also tried to put on `build.gradle` for this `Amount` defined as scalar type this:

```
apollo {
    customTypeMapping = [
            "Amount": "java.util.Map"
    ]
}
```
Because I saw that is registered in apollo library in class `com.apollographql.apollo.api.ScalarTypeAdapters:95`, but I guess this class is the one that works with runtime code, not in building time and that's why I get this error when compiling:

```
TransactionSearchQuery.java:973: error: cannot find symbol
                        final Map.Mapper mapFieldMapper = new java.util.Map.Mapper();
                                 ^
  symbol:   class Mapper
  location: interface Map
```

Is there anything am I missing to correctly parse or setup this field? Thanks!

**Comment by martinbonnin** [comment]
Sorry for the delay, I was off these last days. Apollo Android does not support mapping custom scalar to generic Java/Kotlin types. What you can do is use a wrapper class:

```
package com.example

class JavaAmount {
  Map<String, Object> map;
}
```

and then use that in your mapping:

```
apollo {
    customTypeMapping = [
            "Amount": "com.example.JavaAmount"
    ]
}
```

**Comment by quim3ra** [comment]
Will try that ASAP, thanks for the suggestion

**Comment by cbelizone2y** [comment]
Wil try ASAP, thank you!

**Comment by quim3ra** [comment]
> @cbelizone2y did it work? Anything else I can help with here?

I need yet to test it, sorry for making you wait, let's see if tomorrow I have time to check this solution.

**Comment by martinbonnin** [comment]
Sounds good, thanks for the update!

**Comment by martinbonnin** [comment]
@cbelizon anything else I can help with?

**Comment by martinbonnin** [comment]
Closing for now. Let me know if you want me to reopen.
