### ISSUE TITLE
[dev-3.x] Subscriptions failing on Android when a cache is used

### ISSUE THREAD

**Issue by martinraison** [apollographql/apollo-android#3128]
**Summary**
On Android, on 3.x, subscriptions fail when the client is configured with a cache. I'm posting a minimal repro in case it can help

**Version**
3.0-dev11

**Description**
As promised, I'm posting a repro for the other issue I've had so far with the dev-3.x branch: https://github.com/martinraison/kmm-repro-android-subscription-cache-crash

The repro is almost the same as for #3127, the only difference is I'm configuring the client to use a store (`RealApolloStore` backed by a `MemoryCache`). This causes the subscription to fail on Android with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.example.repro.android, PID: 7629
    java.lang.IllegalArgumentException: Flow has more than one element
        at kotlinx.coroutines.flow.FlowKt__ReduceKt$single$$inlined$collect$1.emit(Collect.kt:135)
        at com.apollographql.apollo3.interceptor.cache.ApolloCacheInterceptor$proceed$$inlined$map$1$2.emit(Collect.kt:137)
        at com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.FlowKt__LimitKt$takeWhile$lambda-9$$inlined$collectWhile$1.emit(Limit.kt:145)
        at com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Unknown Source:2)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:350)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

It looks like at some point, `ApolloCacheInterceptor` assumes there's only a single value in the flow (which is wrong for a subscription) and calls `.single()`. I'm completely unfamiliar with the code so I might be off-track though.

(The iOS version is also failing, but that's the issue reported in #3127)

**Comment by martinraison** [comment]
I can confirm the fix. Thanks a lot for the very fast resolution!
