### ISSUE TITLE
[dev-3.x] Crash during graphql codegen

### ISSUE THREAD

**Issue by martinraison** [apollographql/apollo-android#3137]
**Summary**
I ran into a crash during graphql codegen, posting a minimal repro

**Version**
3.0.0-dev12-SNAPSHOT

**Description**
Full repro here: https://github.com/martinraison/kmm-repro-graphql-codegen-crash

GraphQL schema:

```graphql
type Cat {
    name: String!
}

type Dog {
    name: String! @deprecated
}

union Animal = Cat | Dog

type Query {
    cat: Cat
}
```

Query file:

```graphql
query CatQuery {
    cat {
        ...AnimalFragment
    }
}

fragment AnimalFragment on Animal {
    ... on Cat {
        name
    }
    ... on Dog {
        name
    }
}
```

Stacktrace (relevant section, obtained with `./gradlew :shared:generateApolloSources --stacktrace`):

```
java.lang.IllegalStateException: Check failed.                                                                                                                             
        at com.apollographql.apollo3.compiler.unified.ir.IrBuilder.merge(IrBuilder.kt:444)                                                                                            
        at com.apollographql.apollo3.compiler.unified.ir.IrRootFieldBuilder.buildFieldSet(IrRootFieldBuilder.kt:201)
        at com.apollographql.apollo3.compiler.unified.ir.IrRootFieldBuilder.buildField(IrRootFieldBuilder.kt:145)  
        at com.apollographql.apollo3.compiler.unified.ir.IrRootFieldBuilder.buildFieldSet(IrRootFieldBuilder.kt:203)
        at com.apollographql.apollo3.compiler.unified.ir.IrRootFieldBuilder.buildField(IrRootFieldBuilder.kt:145)                
        at com.apollographql.apollo3.compiler.unified.ir.IrRootFieldBuilder.build(IrRootFieldBuilder.kt:41)               
        at com.apollographql.apollo3.compiler.unified.ir.IrBuilder.toIr(IrBuilder.kt:251)                                                                                             
        at com.apollographql.apollo3.compiler.unified.ir.IrBuilder.build(IrBuilder.kt:76)                                                                                             
        at com.apollographql.apollo3.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:86)                                                                                            
        at com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask.taskAction(ApolloGenerateSourcesTask.kt:206) 
```

The guilty check is here: https://github.com/apollographql/apollo-android/blob/dev-3.x/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/unified/ir/IrBuilder.kt#L444

I see that the check on the previous line was already commented out, apparently for a similar reason.

**Comment by martinbonnin** [comment]
Ah! That's an interesting one... We have this feature that we carry over the GraphQL `@deprecated` into Kotlin `@Deprecated`. This is nice because it allows to spot from the code that some GraphQL fields have been deprecated but that doesn't map 1:1 anymore for merged fields... 

What about something like:

```kotlin
@Deprecated("The matching GraphQL field is deprecated when queried on: 'Dog'")
val name
```

If multiple occurences of the field are deprecated, we could display a list up there.

**Comment by martinraison** [comment]
I see, thanks for the explanation. That sounds look a reasonable solution!

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/apollo-android/pull/3216
