### ISSUE TITLE
stream was reset: NO_ERROR

### ISSUE THREAD

**Issue by flopes89** [apollographql/apollo-android#3260]
**Summary**
I am creating a client like so

```java
        client = ApolloClient.builder()
            .serverUrl(Env.get(EnvVars.HUB_GQL))
            .build();

```

but when running any sort of request, it fails with

```
com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call for operation 'getArticles'
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onFailure(ApolloServerInterceptor.kt:107) [apollo-runtime-2.5.9.jar:2.5.9]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211) [okhttp-3.12.11.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.12.11.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
	at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:644) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:578) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:558) ~[okhttp-3.12.11.jar:?]
	at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[okio-2.9.0.jar:?]
	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149) ~[okhttp-3.12.11.jar:?]
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-2.9.0.jar:?]
	at okio.RealBufferedSink.write(RealBufferedSink.kt:152) ~[okio-2.9.0.jar:?]
	at okhttp3.RequestBody$1.writeTo(RequestBody.java:73) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.11.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.11.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[okhttp-3.12.11.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201) ~[okhttp-3.12.11.jar:?]
	... 4 more
```

**Version**
JDK 11
apollo.runtime 2.5.9

**Description**
I was following the basic examples, so I'm not sure this is even a bug, but I have no clue why the stream is closing?

**Comment by martinbonnin** [comment]
Looks like your backend didn't like the query you're sending. I'd check on the backend if there are any logs or other things that could help diagnose this.

**Comment by flopes89** [comment]
I closed the ticket because it's probably not a bug. But I'm still struggling. It appears to be related to the *size of the request*. When my query exceeds a certain limit (somwhere in the 2-digit kB), the socket read times out. When it's under, it works fine.
