### ISSUE TITLE
Error with Configuration Cache:  'Task.project' at execution time is unsupported.

### ISSUE THREAD

**Issue by yogurtearl** [apollographql/apollo-android#3642]
**Summary**

executing `generateServiceApolloSources` with [configuration cache turned on](https://docs.gradle.org/7.3/userguide/configuration_cache.html#config_cache:usage) gives:
```
Task `:generateServiceApolloSources` of type `com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask`: invocation of 'Task.project' at execution time is unsupported.
```

Could be from the `project` in this line: 
https://github.com/apollographql/apollo-android/blob/6c863698987b6d0c71984c5e55bcd23a19701b55/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/internal/ApolloGenerateSourcesTask.kt#L192

Info on how to fix it here: 
https://docs.gradle.org/7.3/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

**Version**
apollo-android version `3.0.0-beta05`
gradle `7.3`

**Description**

Stacktrace:
```
Task `:generateServiceApolloSources` of type `com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask`: invocation of 'Task.project' at execution time is unsupported.

org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':ghe-graphql:generateServiceApolloSources' at execution time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:75)
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy109.onProjectAccess(Unknown Source)
	at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1020)
	at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:228)
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
	at com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask.taskAction(ApolloGenerateSourcesTask.kt:19)
```

**Comment by martinbonnin** [comment]
Right 👍 . Nothing has been done to support configuration cache yet. Looks like we should pass `kotlinTargetLanguage` as task input. And certainly use `projectName` instead of `project.name` [there](https://github.com/apollographql/apollo-android/blob/6c863698987b6d0c71984c5e55bcd23a19701b55/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/internal/ApolloGenerateSourcesTask.kt#L287).

**Comment by martinbonnin** [comment]
PR is there: https://github.com/apollographql/apollo-android/pull/3645. Snapshots should be live in ~1h if you want to try.

**Comment by yogurtearl** [comment]
is there a snapshots available before the PR is merged?
if so, any docs on the per-branch snapshot naming to I make sure to get a snapshot version from the right branch?

**Comment by yogurtearl** [comment]
Works with `3.0.0-beta06-SNAPSHOT`. Thanks for the quick response/fix. :)

**Comment by martinbonnin** [comment]
Nice 🎉 
PS: snapshots only happen once PR are merged indeed. Not sure why I thought otherwise. But PR is merged now as you found out 😌

**Comment by martinbonnin** [comment]
Released in `-rc01`
