### ISSUE TITLE
[3.0.0-beta04] crash when using the http cache

### ISSUE THREAD

**Issue by CoreFloDev** [apollographql/apollo-android#3664]
Hi,

**Summary**

```
Fatal Exception: java.lang.IllegalStateException: HTTP cache: no snapshot
       at com.apollographql.apollo3.cache.http.DiskLruHttpCache.read(DiskLruHttpCache.java:28)
       at com.apollographql.apollo3.cache.http.CachingHttpEngine.networkMightThrow(CachingHttpEngine.java:86)
       at com.apollographql.apollo3.cache.http.CachingHttpEngine.execute(CachingHttpEngine.java:39)
       at com.apollographql.apollo3.network.http.HttpNetworkTransport$EngineInterceptor.intercept(HttpNetworkTransport.java:139)
       at com.apollographql.apollo3.network.http.DefaultHttpInterceptorChain.proceed(DefaultHttpInterceptorChain.java:21)
       at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.java:100)
       at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(HttpNetworkTransport.java:2)
       at kotlinx.coroutines.flow.SafeFlow.collectSafely(SafeFlow.java:61)
       at kotlinx.coroutines.flow.AbstractFlow.collect(AbstractFlow.java:212)
       at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlowOperatorImpl.java:195)
       at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlowOperator.java:157)
       at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlowOperator.java:1)
       at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.java:60)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Version**
apollo 3.0.0-beta04

**Description**
It seems to happen randomly when people open the app, it happened twice in 1 week usage only on huawei device so far a Honor 9 and a P20 pro. I wasn't able to reproduce so far on my end

Please let me know if you need more details from me,

Thanks
Flo

**Comment by BoD** [comment]
Thank you for reporting the issue! We'll have a look and get back to you.

**Comment by BoD** [comment]
It was indeed a concurrency issue!

A fix for it has just been merged - so it will be present in the next release. In the meantime you can also try it with the [snapshot](https://github.com/apollographql/apollo-android/tree/dev-3.x#snapshots), or as a temporary (and a bit hacky) workaround you can also in your code treat the `IllegalStateException` as you treat `ApolloNetworkException` - assuming your app will show some kind of "retry" UI in that case instead of crashing.

**Comment by BoD** [comment]
Marking this as resolved as it's been released now
