### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gsancho** [apollographql/apollo-android#465]
When add a one mutation en my file .graphql 
I receive this error message RangeError: Maximum call stack size exceeded

**Thanks a lot!**

**Comment by digitalbuddha** [comment]
Please provide a reproducible test case or sample project.

**Comment by marwanad** [comment]
This might be related to apollo-codegen [[1](https://github.com/apollographql/apollo-codegen/issues/102)][[2](https://github.com/apollographql/apollo-codegen/issues/35)]

**Comment by gsancho** [comment]
RangeError: Maximum call stack size exceeded
    at Set.add (native)
    at Set.<anonymous> (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\core-js\library\modules\_collection.js:40:34)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:98:25)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
    at Compiler.addTypeUsed (C:\Users\gsancho\AndroidStudioProjects\App\app\build\apollo-codegen\node_modules\apollo-codegen\src\compilation.js:102:14)
:app:generateDebugApolloIR FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugApolloIR'.
> Process 'command 'C:\Users\gsancho\AndroidStudioProjects\App\app\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1

**Comment by gsancho** [comment]
MUTATION;

mutation CreateFeelingQuery($input:CreateFeelingInput!) {
  createFeeling(input: $input){
   changedFeeling{
      id
    }
  }
}

**Comment by gsancho** [comment]
@marwanad But the 0.3.0 uses v0.10.9 apollo-codegen. What is the fix?  How to the update?  Can't use the mutations on android project?

**Comment by marwanad** [comment]
Should be fixed with the latest `apollo-codegen` version.
