### ISSUE TITLE
Presence of apollo-android causes react-native app to crash in runtime

### ISSUE THREAD

**Issue by ukasiu** [apollographql/apollo-android#501]
When apollo-android is present in the react native project I get 
```
05-17 23:31:05.707 13967 14007 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-17 23:31:05.707 13967 14007 E AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:187)
05-17 23:31:05.707 13967 14007 E AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:183)
```

**Comment by digitalbuddha** [comment]
Please provide a failing test case or sample project. Apollo  is merely a wrapper for okhttp plus code gen for data models, not sure how/why it would affect react native

**Comment by ukasiu** [comment]
https://github.com/ukasiu/apollo-react-native

**Comment by digitalbuddha** [comment]
Is it compilation error or runtime? Could you kindly run with verbose/stack
trace to get more info. It's difficult to see what is happening. Sanity
check: does same project work sans apollo?

My hunch is that it's some node stuff not playing nicely together.

**Comment by ukasiu** [comment]
It's runtime, I attached the complete stacktrace from logcat in the first comment. Yep, the project works without apollo.

**Comment by digitalbuddha** [comment]
That stack trace is rather short on relevant info. I don't see anything there that has any references to apollo nor do you seem to be pulling any apollo code into your classes. I can take a look in few days but am not familiar with anything react native related.  @ben.schwab have you had any issues with apollo and react native?

**Comment by ukasiu** [comment]
You're right, I was grepping logcat. Below is the full log from the crash:

```
05-18 00:32:20.521  1163 12217 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.apollorn/.MainActivity bnds=[18,182][155,377] (has extras)} from uid 10039 on display 0
05-18 00:32:20.576  1163 12218 I ActivityManager: Start proc 2571:com.apollorn/u0a152 for activity com.apollorn/.MainActivity
05-18 00:32:20.591  2571  2571 I art     : Late-enabling -Xcheck:jni
05-18 00:32:20.694 30562 31111 I PBSessionCacheImpl: Deleted sessionId[5375069788579] from persistence.
05-18 00:32:20.715 30562 30562 W SearchService: Abort, client detached.
05-18 00:32:20.724 30562 30562 E WorkerRegistryImpl: getWorker() is called after WorkerRegistry disposal.
05-18 00:32:20.725 30562 30562 E WorkerRegistryImpl: getWorker() is called after WorkerRegistry disposal.
05-18 00:32:20.794 20558 32640 E ctxmgr  : [ProducerActiveIntervalImpl]closeActiveInterval: Error: ongoing, trying to close
05-18 00:32:20.866 20558 20641 I PlaceInferenceEngine: [anon] Changed inference mode: 105
05-18 00:32:21.043  2571  2571 I InstantRun: starting instant run server: is main process
05-18 00:32:21.055  2571  2571 V fb-UnpackingSoSource: locked dso store /data/user/0/com.apollorn/lib-main
05-18 00:32:21.056  2571  2571 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.apollorn/lib-main
05-18 00:32:21.056  2571  2571 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.apollorn/lib-main
05-18 00:32:21.165  2571  2571 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-18 00:32:21.182  1163  2174 D Sensors : batch called handle:1 sample_ns:66667000 latency_ns:0
05-18 00:32:21.182  1163  2174 D Sensors : bma2x2-accel calling driver setDelay 66 ms
05-18 00:32:21.182  1163  2174 I Sensors : sensors flush called handle:1 
05-18 00:32:21.182  1163  2174 D Sensors : flush called
05-18 00:32:21.195  2571  2590 W unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
05-18 00:32:21.195  2571  2571 W unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
05-18 00:32:21.196  2571  2591 W unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
05-18 00:32:21.232  2571  2590 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-18 00:32:21.232  2571  2590 E AndroidRuntime: Process: com.apollorn, PID: 2571
05-18 00:32:21.232  2571  2590 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at android.os.AsyncTask$3.done(AsyncTask.java:325)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:761)
05-18 00:32:21.232  2571  2590 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method setCallWebSocket(Lokhttp3/Call;)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.apollorn-1/split_lib_dependencies_apk.apk:classes22.dex)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at com.facebook.react.packagerconnection.ReconnectingWebSocket.connect(ReconnectingWebSocket.java:71)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at com.facebook.react.packagerconnection.JSPackagerClient.init(JSPackagerClient.java:84)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:158)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:132)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-18 00:32:21.232  2571  2590 E AndroidRuntime:  ... 3 more
05-18 00:32:21.235  1163  1226 W ActivityManager:   Force finishing activity com.apollorn/.MainActivity
05-18 00:32:21.239  2571  2591 I Process : Sending signal. PID: 2571 SIG: 9
05-18 00:32:21.246   286   286 E lowmemorykiller: Error writing /proc/2571/oom_score_adj; errno=22
05-18 00:32:21.307  1163 29224 I OpenGLRenderer: Initialized EGL, version 1.4
05-18 00:32:21.307  1163 29224 D OpenGLRenderer: Swap behavior 1
05-18 00:32:21.341  1163 12215 D Sensors : batch called handle:1 sample_ns:66667000 latency_ns:100000000
05-18 00:32:21.341  1163 12215 D Sensors : bma2x2-accel calling driver setDelay 66 ms
05-18 00:32:21.341  1163  1224 I ActivityManager: Process com.apollorn (pid 2571) has died
```

**Comment by digitalbuddha** [comment]
Here's the meat of it 

05-18 00:32:21.232  2571  2590 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method setCallWebSocket(Lokhttp3/Call;)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.apollorn-1/split_lib_dependencies_apk.apk:classes22.dex)
05-18 00:32:21.232

No idea why this class is missing from your class path but that is not an apollo error. Maybe Multidex or proguard?

**Comment by ukasiu** [comment]
Without apollo it works - I'd suspect a dependency conflict.

**Comment by digitalbuddha** [comment]
Seems related
http://stackoverflow.com/questions/42209251/okhttp3-java-lang-nosuchmethoderror-no-virtual-method-setcallwebsocket

**Comment by digitalbuddha** [comment]
One more... http://stackoverflow.com/questions/43020878/react-native-activity-crashes-probably-related-to-packaging-okhttp3

**Comment by ukasiu** [comment]
Thanks a lot. Forcing okhttp to a specific version solves the issue. Maybe it could be somehow included in the docs.

**Comment by BenSchwab** [comment]
@ukasiu Was forcing a specific version enough? I had this issue a long time ago when integrating at Airbnb, and we had to fork to change a couple constants
https://github.com/airbnb/apollo-android/commit/d465d993a998165202f9f3c803b6e2f6d88f090b

**Comment by digitalbuddha** [comment]
Seems like react native is using old version maybe report as issue on their
end?

**Comment by ukasiu** [comment]
It's probably off-topic, but why doesn't gradle warn about such conflicts? Ruby Bundler wouldn't allow it to happen, unless version were too widely specified.

okhttp is now 3.8.0, if they update the conflict will still exists.
