### ISSUE TITLE
Adding HttpLoggingInterceptor as an application interceptor to OkHttp results in a ParseException

### ISSUE THREAD

**Issue by aadithyabk** [apollographql/apollo-android#510]
**Code snippe**t:

`HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);
OkHttpClient okHttpClient = new OkHttpClient.Builder()
                                                    .addInterceptor(logging)
                                                    .build();`

**Stacktrace**:
`java.io.EOFException: End of input
                                                                                at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.nextNonWhitespace(BufferedSourceJsonReader.java:945)
                                                                                at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:332)
                                                                                at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)
                                                                                at com.apollographql.apollo.internal.interceptor.HttpResponseBodyParser.parse(HttpResponseBodyParser.java:41)
                                                                                at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:80)
                                                                                at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.intercept(ApolloParseInterceptor.java:48)
                                                                                at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceed(RealApolloInterceptorChain.java:41)
                                                                                at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor.intercept(ApolloCacheInterceptor.java:83)
                                                                                at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceed(RealApolloInterceptorChain.java:41)
                                                                                at com.apollographql.apollo.internal.RealApolloCall.execute(RealApolloCall.java:86) `

Version: 0.3.0
Device: Nexus 5, 6.0

**Comment by digitalbuddha** [comment]
You can't read the body in a logging interceptor as reading the body can only be done once.
