### ISSUE TITLE
java.lang.IllegalStateException: Stack is empty

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#542]
Apollo is failing to parse a response from our GraphQL server, and I'm not entirely sure why. I suspect that it doesn't like one of the fields having a `null` value (`product_groups`), when its expecting a `List`. 

I'm using version: `0.3.2`

Here is the stacktrace:

```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:91)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$000(ApolloParseInterceptor.java:28)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:57)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:100)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalStateException: Stack is empty.
	at com.apollographql.apollo.internal.util.SimpleStack.pop(SimpleStack.java:28)
	at com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer.didParseList(ResponseNormalizer.java:102)
	at com.apollographql.apollo.internal.reader.RealResponseReader.readObjectList(RealResponseReader.java:202)
	at com.apollographql.apollo.internal.reader.RealResponseReader.read(RealResponseReader.java:61)
	at com.ibotta.android.SearchGraphQL$Result$Mapper.map(SearchGraphQL.java:411)
	at com.ibotta.android.SearchGraphQL$Search$Mapper$1.read(SearchGraphQL.java:280)
	at com.ibotta.android.SearchGraphQL$Search$Mapper$1.read(SearchGraphQL.java:278)
	at com.apollographql.apollo.internal.reader.RealResponseReader.readObjectList(RealResponseReader.java:196)
	at com.apollographql.apollo.internal.reader.RealResponseReader.read(RealResponseReader.java:61)
	at com.ibotta.android.SearchGraphQL$Search$Mapper.map(SearchGraphQL.java:288)
	at com.ibotta.android.SearchGraphQL$Data$Mapper$1.read(SearchGraphQL.java:198)
	at com.ibotta.android.SearchGraphQL$Data$Mapper$1.read(SearchGraphQL.java:196)
	at com.apollographql.apollo.internal.reader.RealResponseReader.readObject(RealResponseReader.java:157)
	at com.apollographql.apollo.internal.reader.RealResponseReader.read(RealResponseReader.java:55)
	at com.ibotta.android.SearchGraphQL$Data$Mapper.map(SearchGraphQL.java:205)
	at com.ibotta.android.SearchGraphQL$Data$Mapper.map(SearchGraphQL.java:187)
	at com.apollographql.apollo.internal.interceptor.HttpResponseBodyParser$1.read(HttpResponseBodyParser.java:59)
	at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
	at com.apollographql.apollo.internal.interceptor.HttpResponseBodyParser.parse(HttpResponseBodyParser.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:80)
	... 8 more
```

Here is the query I'm using:

```
query SearchGraphQL($term: String, $limit: Int) {
  search(term: $term, limit: $limit) {
    results {
      id
      type
      display_type
      content {
        id
        type
        name
        link
        sort_order
        ... on Offer {
          amount
          bonuses
          product_groups {
            id
            products
          }
        }
      }
    }
  }
}
```

And here is the response using this query, captured from GraphiQL. Note, in this payload the second `Offer` type entry has a `null` value for `product_groups`. **I don't think this should cause the exception I'm seeing**: 

```
{
  "data": {
    "search": {
      "results": [
        {
          "id": "-100",
          "type": "ContentModule",
          "display_type": "rows",
          "content": [
            {
              "id": "96380",
              "type": "Offer",
              "name": "Bud Light Lime Lime-A-Rita® AND Fresh or Frozen Chicken or Seafood",
              "link": "retailer/any/offer/96380",
              "sort_order": null,
              "amount": 3,
              "bonuses": null,
              "product_groups": [
                {
                  "id": "6374",
                  "products": [
                    "00018200199875",
                    "00018200209857",
                    "00018200209932",
                    "00018200229923",
                    "00018200229886",
                    "00018200229893",
                    "00018200958144",
                    "00018200958878",
                    "00018200958328",
                    "00018200958762",
                    "00018200960451",
                    "00018200960468",
                    "00018200960475",
                    "00018200960628",
                    "00018200960918",
                    "00018200957956",
                    "00018200958441",
                    "00018200958458",
                    "00018200957949",
                    "00018200958472",
                    "00018200958489",
                    "00018200958311",
                    "00018200958755",
                    "00018200958847",
                    "00018200960291",
                    "00018200140365",
                    "00018200983023",
                    "00018200958267",
                    "00018200958373",
                    "00018200982958",
                    "00018200140235",
                    "00018200970078",
                    "00018200140273",
                    "00018200140280",
                    "00018200140303",
                    "00018200958106",
                    "00018200140341",
                    "00018200958120",
                    "00018200960314",
                    "00018200958380",
                    "00018200982927",
                    "00018200958137",
                    "00018200960932",
                    "00018200969317",
                    "00018200958113",
                    "00018200958465",
                    "00018200958496",
                    "00018200281358",
                    "00018200281341",
                    "00018200281365",
                    "00018200958861",
                    "00018200200038",
                    "00018200200069",
                    "00018200200076",
                    "00018200200045",
                    "00018200200106",
                    "00018200200052",
                    "00018200200083",
                    "00018200229992",
                    "00018200283062",
                    "00018200283093",
                    "00018200283109",
                    "00018200283079",
                    "00018200283130",
                    "00018200283086",
                    "00018200283116",
                    "00018200984075",
                    "00018200200175",
                    "00018200200182",
                    "00018200283208",
                    "00018200283222",
                    "00018200283239",
                    "00018200283246",
                    "00018200283253",
                    "00018200283215",
                    "00018200200229",
                    "00018200200342",
                    "00018200283482",
                    "00018200283567",
                    "00018200283611",
                    "00018200283574",
                    "00018200200267",
                    "00018200283352",
                    "00018200283451",
                    "00018200283468",
                    "00018200283475",
                    "00018200283758",
                    "00018200283369",
                    "00018200283987",
                    "00018200283949",
                    "00018200283932"
                  ]
                },
                {
                  "id": "6375",
                  "products": []
                }
              ]
            },
            {
              "id": "96107",
              "type": "Offer",
              "name": "Budweiser® OR Bud Light® AND Snack Items",
              "link": "retailer/any/offer/96107",
              "sort_order": null,
              "amount": 2,
              "bonuses": null,
              "product_groups": null
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by sav007** [comment]
@eschlenz could you please try snapshot version, I believe it has been fixed in it.

**Comment by sav007** [comment]
Closing for now.

**Comment by eschlenz** [comment]
@sav007 

https://media.giphy.com/media/W9WSk4tEU1aJW/giphy.gif

Yes, indeed, that worked. Thanks!
