### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by adamame** [apollographql/apollo-android#575]
I've been getting an ArrayIndexOutOfBoundsException while parsing a response in the `didResolve()` method in `ResponseNormalizer`.  The code is this line:
```
path.remove(path.size() - 1);
```

and path.size() is 0

Using `0.4.0-SNAPSHOT`

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
      at java.util.ArrayList.remove(ArrayList.java:480)
      at com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer.didResolve(ResponseNormalizer.java:52)
      at com.apollographql.apollo.internal.reader.RealResponseReader.didResolve(RealResponseReader.java:194)
      at com.apollographql.apollo.internal.reader.RealResponseReader.readList(RealResponseReader.java:140)
      at com.ibotta.android.ModulesGraphQLQuery$Module$Mapper.map(ModulesGraphQLQuery.java:563)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper$1$1.read(ModulesGraphQLQuery.java:304)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper$1$1.read(ModulesGraphQLQuery.java:301)
      at com.apollographql.apollo.internal.reader.RealResponseReader$ListItemReader.readObject(RealResponseReader.java:251)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper$1.read(ModulesGraphQLQuery.java:301)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper$1.read(ModulesGraphQLQuery.java:298)
      at com.apollographql.apollo.internal.reader.RealResponseReader.readList(RealResponseReader.java:133)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper.map(ModulesGraphQLQuery.java:298)
      at com.ibotta.android.ModulesGraphQLQuery$Data$Mapper.map(ModulesGraphQLQuery.java:293)
      at com.apollographql.apollo.internal.interceptor.HttpResponseBodyParser$1.read(HttpResponseBodyParser.java:57)
      at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
      at com.apollographql.apollo.internal.interceptor.HttpResponseBodyParser.parse(HttpResponseBodyParser.java:51)
      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:93)
```

And the response looks like this:
```
{
  "data": {
    "modules": [
      {
        "content": [
          {
            "id": "1",
            "info": null
          },
          {
            "id": "2",
            "info": null
          }
        ]
      },
      {
        "content": [
          {
            "id": "3",
            "info": {
              "android": {
                "id": "btn-1a1474fc05e4c7ed",
                "url": null
              },
              "ios": {
                "id": "btn-3e948def5783f2cf",
                "url": null
              }
            }
          },
          {
            "id": "4",
            "info": {
              "android": {
                "id": "btn-1a1474fc05e4c7ed",
                "url": null
              },
              "ios": {
                "id": "btn-3e948def5783f2cf",
                "url": null
              }
            }
          }
        ]
      }
   }
}
```

"info" and all of it's children are nullable fields.   If I remove the "info" field from the query, the response parses just fine.

Could this be related to #552 ?

**Comment by sav007** [comment]
Could you please share the generated apollo models? And if it possible the generated *.json under the folder `.../build/generated/source/apollo/generatedIR`

**Comment by eschlenz** [comment]
@sav007 

Would you be open to us sharing this information with you privately? What you are requesting would expose more than we'd like to about our system in a public forum.

-- OR --

Is there a subset of things we can provide that would help you identify and address this issue?

**Comment by sav007** [comment]
@eschlenz I understand, of course you can share this info with me, just ping me in slack

**Comment by sav007** [comment]
hey @eschlenz @adamame is there any additional info you can share with me?

**Comment by adamame** [comment]
@sav007 I've posted the info in a slack dm.  Sorry for the delay
