### ISSUE TITLE
NPE while Mapping Fragments

### ISSUE THREAD

**Issue by adamame** [apollographql/apollo-android#629]
@sav007 We've recently been getting a `NullPointerException` in a generated query when mapping to a Fragment.  The generated code is calling
```Utils.checkNotNull(ourFragment, "ourFragment == null")```
but the Fragments are marked as nullable.

```
Caused by: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
                         E      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:102)
                         E      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.intercept(ApolloParseInterceptor.java:51)
                         E      at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceed(RealApolloInterceptorChain.java:38)
                         E      at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor.intercept(ApolloCacheInterceptor.java:65)
                         E      at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceed(RealApolloInterceptorChain.java:38)
                         E      at com.apollographql.apollo.internal.fetcher.CacheFirstFetcher$CacheFirstInterceptor.intercept(CacheFirstFetcher.java:40)
                         E      at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceed(RealApolloInterceptorChain.java:38)
                         E      at com.apollographql.apollo.internal.RealApolloCall.execute(RealApolloCall.java:130)
```

I'll DM you with more details

**Comment by adamame** [comment]
Looks like this is the culprit: https://github.com/apollographql/apollo-android/blob/afc25d82566de99f24e8c6e227a97f7c2addcf79/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/FragmentsResponseMapperBuilder.kt#L88

fieldSpec.type.isOptional() is null in our case

**Comment by eschlenz** [comment]
FYI, this started happening in the 0.4.1-16 snapshot
