### ISSUE TITLE
Query variables in request being obfuscated,any proguard rules for generated code?

### ISSUE THREAD

**Issue by 80998062** [apollographql/apollo-android#648]
After using Proguard, the **apollo-android** totally can't work with the status code **400 Bad Request** as message.

> the output of trace stacks: 

```
W/System.err: com.b.a.c.c: HTTP 400 Bad Request
W/System.err:     at com.b.a.e.c.b.a(ApolloParseInterceptor.java:95)
W/System.err:     at com.b.a.e.c.b.a(ApolloParseInterceptor.java:48)
W/System.err:     at com.b.a.e.c.e.a(RealApolloInterceptorChain.java:41)
W/System.err:     at com.b.a.e.c.a.a(ApolloCacheInterceptor.java:84)
W/System.err:     at com.b.a.e.c.e.a(RealApolloInterceptorChain.java:41)
W/System.err:     at com.b.a.e.c.a(RealApolloCall.java:128)
W/System.err:     at com.b.a.g.a$1.a(Rx2Apollo.java:83)
W/System.err:     at io.a.e.e.d.a.b(SingleCreate.java:39)
W/System.err:     at io.a.o.a(Single.java:2693)
W/System.err:     at io.a.e.e.d.l.b(SingleMap.java:33)
W/System.err:     at io.a.o.a(Single.java:2693)
W/System.err:     at io.a.e.e.d.o$a.run(SingleSubscribeOn.java:89)
W/System.err:     at io.a.n$1.run(Scheduler.java:138)
W/System.err:     at io.a.e.g.f.run(ScheduledRunnable.java:59)
W/System.err:     at io.a.e.g.f.call(ScheduledRunnable.java:51)...
```

When inspect the network in the Chrome,I found it seems that the **Proguard**  obfuscated too much to change the query variables :

```json
query: "mutation GetAuthCode($phone: String!, $purpose: String!) {  sendPhoneMessage(data: {phone: $phone, purpose: $purpose}) {    __typename    sent  }}"
variables: {a: "15757161279", b: "reset_password"}
a: "15757161279"
b: "reset_password"
```

>  the `a` and `b` are supposed to be `phone` and `password`

So the server returns the status code :**400 Bad Request**.

**Besides**,my snippet related in *proguard-rules.pro* is as follow:

```
#-keep,allowobfuscation @interface javax.annotation.Generated("Apollo GraphQL")
#-keep @javax.annotation.Generated("Apollo GraphQL") class * {*;}
#-keepclassmembers class * {
#    @javax.annotation.Generated("Apollo GraphQL") *;
#}

-keep public class * implements com.apollographql.apollo.api.Query
-keep public class * implements com.apollographql.apollo.api.Mutation
```

 (:o 」∠)_but unfortunately it is no use ,so how can I update my proguard rules to *exclude the generated code* by **appollo**?

Sorry that I am unskilled with **Proguard** configuration , if anyone can give me *a working example*,much appreciated. ( ˉ ⌓ ˉ ๑)﻿﻿

**Comment by sav007** [comment]
Thanks for the reporting, will investigate why it happens it should work with default proguard rules.

**Comment by sav007** [comment]
One question for you, what version of Apollo you are using

**Comment by 80998062** [comment]
Sorry for the late reply,I am using version  `0.3.1` for now.

> for more details,I'd like take a mutation method as example:

```java
@Generated("Apollo GraphQL")
public final class GetAuthCode implements Mutation<GetAuthCode.Data, GetAuthCode.Data, GetAuthCode.Variables> {
  public static final String OPERATION_DEFINITION = "mutation GetAuthCode($phone: String!, $purpose: String!) {\n"
      + "  sendPhoneMessage(data: {phone: $phone, purpose: $purpose}) {\n"
      + "    __typename\n"
      + "    sent\n"
      + "  }\n"
      + "}";
      
      //
}
```

and,

```java
  public static final class Variables extends Operation.Variables {
    private final @Nonnull String phone;

    private final @Nonnull String purpose;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@Nonnull String phone, @Nonnull String purpose) {
      this.phone = phone;
      this.purpose = purpose;
      this.valueMap.put("phone", phone);
      this.valueMap.put("purpose", purpose);
    }
    
    // ...
 }
```



**Here** is part of my *mapping.txt* created by **Proguard**,which shows the original class, method, and field names mapped to the obfuscated names:

```Java
com.sinyuk.sinyuk.GetAuthCode -> com.sinyuk.sinyuk.q:
    com.apollographql.apollo.api.OperationName OPERATION_NAME -> b
    com.sinyuk.sinyuk.GetAuthCode$Variables variables -> c
    44:48:void <init>(java.lang.String,java.lang.String) -> <init>
    52:52:java.lang.String queryDocument() -> a
    57:57:com.sinyuk.sinyuk.GetAuthCode$Data wrapData(com.sinyuk.sinyuk.GetAuthCode$Data) -> a
    62:62:com.sinyuk.sinyuk.GetAuthCode$Variables variables() -> e
    67:67:com.apollographql.apollo.api.ResponseFieldMapper responseFieldMapper() -> c
    71:71:com.sinyuk.sinyuk.GetAuthCode$Builder builder() -> f
    76:76:com.apollographql.apollo.api.OperationName name() -> d
    24:24:java.lang.Object wrapData(com.apollographql.apollo.api.Operation$Data) -> a
    24:24:com.apollographql.apollo.api.Operation$Variables variables() -> b
    35:35:void <clinit>() -> <clinit>
com.sinyuk.sinyuk.GetAuthCode$1 -> com.sinyuk.sinyuk.q$1:
    35:35:void <init>() -> <init>
com.sinyuk.sinyuk.GetAuthCode$Builder -> com.sinyuk.sinyuk.q$a:
    java.lang.String phone -> a
    java.lang.String purpose -> b
    112:113:void <init>() -> <init>
    116:117:com.sinyuk.sinyuk.GetAuthCode$Builder phone(java.lang.String) -> a
    121:122:com.sinyuk.sinyuk.GetAuthCode$Builder purpose(java.lang.String) -> b
    126:128:com.sinyuk.sinyuk.GetAuthCode build() -> a
com.sinyuk.sinyuk.GetAuthCode$Data -> com.sinyuk.sinyuk.q$b:
    com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage sendPhoneMessage -> a
    java.lang.String $toString -> b
    int $hashCode -> c
    boolean $hashCodeMemoized -> d
    141:143:void <init>(com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage) -> <init>
    146:146:com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage sendPhoneMessage() -> a
    151:156:java.lang.String toString() -> toString
    161:168:boolean equals(java.lang.Object) -> equals
    173:180:int hashCode() -> hashCode
com.sinyuk.sinyuk.GetAuthCode$Data$Mapper -> com.sinyuk.sinyuk.q$b$a:
    com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage$Mapper sendPhoneMessageFieldMapper -> a
    com.apollographql.apollo.api.Field[] fields -> b
    183:198:void <init>() -> <init>
    207:208:com.sinyuk.sinyuk.GetAuthCode$Data map(com.apollographql.apollo.api.ResponseReader) -> b
    183:183:java.lang.Object map(com.apollographql.apollo.api.ResponseReader) -> a
com.sinyuk.sinyuk.GetAuthCode$Data$Mapper$1 -> com.sinyuk.sinyuk.q$b$a$1:
    com.sinyuk.sinyuk.GetAuthCode$Data$Mapper this$0 -> a
    198:198:void <init>(com.sinyuk.sinyuk.GetAuthCode$Data$Mapper) -> <init>
    200:200:com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage read(com.apollographql.apollo.api.ResponseReader) -> b
    198:198:java.lang.Object read(com.apollographql.apollo.api.ResponseReader) -> a
com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage -> com.sinyuk.sinyuk.q$c:
    java.lang.String __typename -> a
    java.lang.Boolean sent -> b
    java.lang.String $toString -> c
    int $hashCode -> d
    boolean $hashCodeMemoized -> e
    224:227:void <init>(java.lang.String,java.lang.Boolean) -> <init>
    234:234:java.lang.Boolean sent() -> a
    239:245:java.lang.String toString() -> toString
    250:258:boolean equals(java.lang.Object) -> equals
    263:272:int hashCode() -> hashCode
com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage$Mapper -> com.sinyuk.sinyuk.q$c$a:
    com.apollographql.apollo.api.Field[] fields -> a
    275:278:void <init>() -> <init>
    283:285:com.sinyuk.sinyuk.GetAuthCode$SendPhoneMessage map(com.apollographql.apollo.api.ResponseReader) -> b
    275:275:java.lang.Object map(com.apollographql.apollo.api.ResponseReader) -> a
com.sinyuk.sinyuk.GetAuthCode$Variables -> com.sinyuk.sinyuk.q$d:
    java.lang.String phone -> a
    java.lang.String purpose -> b
    java.util.Map valueMap -> c
    84:91:void <init>(java.lang.String,java.lang.String) -> <init>
    103:103:java.util.Map valueMap() -> a
```

Thus,as I mentioned **above**,when inspect the network in the Chrome,I got the status code :**400 Bad Request**.

```json
query: "mutation GetAuthCode($phone: String!, $purpose: String!) {  sendPhoneMessage(data: {phone: $phone, purpose: $purpose}) {    __typename    sent  }}"
variables: {a: "15757161279", b: "reset_password"}
a: "15757161279"
b: "reset_password"
```

Cause the **variables** `phone` and `password` became the obfuscated names: `a` and `b`;

And I try to use these rules:

```Java
#-keep public class * implements com.apollographql.apollo.api.Query
#-keep public class * implements com.apollographql.apollo.api.Mutation
#-keep public class * implements com.apollographql.apollo.api.Operation.Data
#-keep public class * implements com.apollographql.apollo.api.ResponseFieldMapper
#-keep public class * extends com.apollographql.apollo.api.Operation.Variables
-keep public class com.sinyuk.sinyuk.GetAuthCode
-keep public class com.sinyuk.sinyuk.OtherClassGeneratedByApollo
```

**but** it's frustrating that still can't preserve anything generated by **apollo** .

So any advices on **Proguard** rules?

**Comment by sav007** [comment]
Could you please give it a try `0.4.1` version

**Comment by 80998062** [comment]
Yes I've tried 0.4.1,but I found a big change which could affect the whole project.

 not like the document said before:

    //Create a query object
    EpisodeHeroName query = EpisodeHeroName.builder().episode(Episode.EMPIRE).build();
    
    //RxJava2 Single
    Single<EpisodeHeroName.Data> single2 = Rx2Apollo.from(apolloCall);

 after looking up in the new code,I found that:

     @Nonnull public static <T> Observable<Response<T>> from(@Nonnull final ApolloCall<T> originalCall) {
        checkNotNull(originalCall, "call == null");
        }

Every Rx2Apollo.from() methods return Single before became Observable now,which is not acceptable for me .

It should be suppress a breaking change from previous version,I think ⊙﹏⊙

**Comment by sav007** [comment]
Yes that was done intentionally as now call can emit multiple response if `com.apollographql.apollo.fetcher.ApolloResponseFetchers#CACHE_AND_NETWORK` is enabled.

**Comment by 80998062** [comment]
Yes I've tried `0.4.1`,but I found a **big change** which could affect the whole project.

>  not like the document said before:

```java
//Create a query object
EpisodeHeroName query = EpisodeHeroName.builder().episode(Episode.EMPIRE).build();

//RxJava2 Single
Single<EpisodeHeroName.Data> single2 = Rx2Apollo.from(apolloCall);
```

>  after looking up in the new code,I found that:

```java
 @Nonnull public static <T> Observable<Response<T>> from(@Nonnull final ApolloCall<T> originalCall) {
    checkNotNull(originalCall, "call == null");
    }
```

**Every** `Rx2Apollo.from()` methods return `Single` before became `Observable` now,which is not acceptable for me .

It should be suppress a *breaking change* from previous version,I think ⊙﹏⊙





Oh, and not to mention,`0.4.1` version still not work  for me.

From the *seed.text* which lists the things that were not obfuscated,I found the **Proguard** has keep the classes generated by **Apollo**:

```java
com.xinshu.xinshu.GetProfile: com.apollographql.apollo.api.OperationName OPERATION_NAME
com.xinshu.xinshu.GetProfile: com.apollographql.apollo.api.Operation$Variables variables
com.xinshu.xinshu.GetProfile: GetProfile()
com.xinshu.xinshu.GetProfile: java.lang.String operationId()
com.xinshu.xinshu.GetProfile: java.lang.String queryDocument()
com.xinshu.xinshu.GetProfile: com.xinshu.xinshu.GetProfile$Data wrapData(com.xinshu.xinshu.GetProfile$Data)
com.xinshu.xinshu.GetProfile: com.apollographql.apollo.api.Operation$Variables variables()
com.xinshu.xinshu.GetProfile: com.apollographql.apollo.api.ResponseFieldMapper responseFieldMapper()
com.xinshu.xinshu.GetProfile: com.xinshu.xinshu.GetProfile$Builder builder()
com.xinshu.xinshu.GetProfile: com.apollographql.apollo.api.OperationName name()
com.xinshu.xinshu.GetProfile: java.lang.Object wrapData(com.apollographql.apollo.api.Operation$Data)
com.xinshu.xinshu.GetProfile: void <clinit>()
com.xinshu.xinshu.GetProfile$1: GetProfile$1()
com.xinshu.xinshu.GetProfile$Builder: GetProfile$Builder()
com.xinshu.xinshu.GetProfile$Data$Mapper: GetProfile$Data$Mapper()
com.xinshu.xinshu.GetProfile$Me$Mapper: GetProfile$Me$Mapper()
```

But it didn't preserve the inner classes , so for example:

```java
@Generated("Apollo GraphQL")
public final class GetProfile implements Query<GetProfile.Data, GetProfile.Data, Operation.Variables> {
	 public static class Data implements Operation.Data {
       public final @Nullable Me me;
       public static class Me {
         static final ResponseField[] $responseFields;
         public final @Nonnull String __typename;
         public final @Nonnull String id;
         // ...fileds
         public static final class Mapper implements ResponseFieldMapper<Me>;
       }
	 }
}
```

It seems that the **Proguard** has obfuscated class `Me`, so I got the `logcat` like:

```json
{
"b":"UserNode",
"c":"Sep 6, 2017 ",
"d":"e3cd7b83a6c078",
"e":"Sinyuk",
"f":"baebb24db2f74"
}
```

And I want to mapper this class to my own entity by **GSON**, but I can't to do that with *obfuscated* field names.

I try to add *additional* rules to keep the inner classes:

```
-keepattributes InnerClasses
-keep class com.xinshu.xinshu.GetProfile**
-keepclassmembers class com.xinshu.xinshu.GetProfile** { *;}
```

This did the trick for me:

>  *seed.text*

```
comm.xinshu.xinshu.GetProfile$Data$1: com.xinshu.xinshu.GetProfile$Data this$0
com.xinshu.xinshu.GetProfile$Data$1: GetProfile$Data$1(com.xinshu.xinshu.GetProfile$Data)
com.xinshu.xinshu.GetProfile$Data$1: void marshal(com.apollographql.apollo.api.ResponseWriter)
com.xinshu.xinshu.GetProfile$Data$Mapper
com.xinshu.xinshu.GetProfile$Data$Mapper: com.xinshu.xinshu.GetProfile$Me$Mapper meFieldMapper
com.xinshu.xinshu.GetProfile$Data$Mapper: GetProfile$Data$Mapper()
com.xinshu.xinshu.GetProfile$Data$Mapper: com.xinshu.xinshu.GetProfile$Data map(com.apollographql.apollo.api.ResponseReader)
com.xinshu.xinshu.GetProfile$Data$Mapper: java.lang.Object map(com.apollographql.apollo.api.ResponseReader)
com.xinshu.xinshu.GetProfile$Data$Mapper$1
com.xinshu.xinshu.GetProfile$Data$Mapper$1: com.xinshu.xinshu.GetProfile$Data$Mapper this$0
com.xinshu.xinshu.GetProfile$Data$Mapper$1: GetProfile$Data$Mapper$1(com.xinshu.xinshu.GetProfile$Data$Mapper)
com.xinshu.xinshu.GetProfile$Data$Mapper$1: com.xinshu.xinshu.GetProfile$Me read(com.apollographql.apollo.api.ResponseReader)
com.xinshu.xinshu.GetProfile$Data$Mapper$1: java.lang.Object read(com.apollographql.apollo.api.ResponseReader)
com.xinshu.xinshu.GetProfile$Me
com.xinshu.xinshu.GetProfile$Me: com.apollographql.apollo.api.ResponseField[] $responseFields
com.xinshu.xinshu.GetProfile$Me: java.lang.String __typename
com.xinshu.xinshu.GetProfile$Me: java.util.Date lastLogin
com.xinshu.xinshu.GetProfile$Me: java.lang.String id
com.xinshu.xinshu.GetProfile$Me: java.lang.String username
```

Since there are **a lot of** classes generated by **Apollo**,it will take time to add rules for each one and may be a bit *overkill*.

But  there is no better way of achieving this I could figure out  (´ｰ ｀)ｷﾗｯ

Do you have any idea? Plz share |´-`）.｡oO

**Comment by sav007** [comment]
Oh so you are using your own GSON to serialize generated models? Then yes you need custom proguard rules. The easy way is to add the whole package to be ignored by proguard, smth like:
```
-keep public class comm.xinshu.xinshu.** {
   *;
}
```

**Comment by sav007** [comment]
Closing.

**Comment by Belka1000867** [comment]
I also have similar problem: 
`com.apollographql.apollo.b.c: HTTP 400 
        at com.apollographql.apollo.d.c.b.a(ApolloParseInterceptor.java:95)
        at com.apollographql.apollo.d.c.b$1.a(ApolloParseInterceptor.java:1028)
        at com.apollographql.apollo.d.c.c$1$1.a(ApolloServerInterceptor.java:100)
        at d.y$a.b(RealCall.java:153)
        at d.a.b.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)`
