### ISSUE TITLE
Nesting too deep error thrown 

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#736]
This error is thrown for a query with lots of nesting levels. Isn't there an override for the number for nest levels? Is the impact so significant on performance if I have 5-10 more nest levels?

**Comment by sav007** [comment]
Could you please provide a stack trace for this error? Is it runtime error?

**Comment by nicusorflorin** [comment]
`* What went wrong:
Execution failed for task ':graphql-module:generateDebugApolloClasses'.
> Nesting too deep at $.operations[2].fields[0].fields[1].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':graphql-module:generateDebugApolloClasses'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.squareup.moshi.JsonDataException: Nesting too deep at $.operations[2].fields[0].fields[1].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields
	at com.squareup.moshi.JsonReader.pushScope(JsonReader.java:203)
	at com.squareup.moshi.JsonUtf8Reader.beginArray(JsonUtf8Reader.java:107)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:74)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
	at com.apollographql.apollo.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:16)
	at com.apollographql.apollo.gradle.ApolloClassGenTask$1.execute(ApolloClassGenTask.java:51)
	at com.apollographql.apollo.gradle.ApolloClassGenTask$1.execute(ApolloClassGenTask.java:46)
	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:46)
	at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:39)
	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.outOfDate(ChangesOnlyIncrementalTaskInputs.java:27)
	at com.apollographql.apollo.gradle.ApolloClassGenTask.generateClasses(ApolloClassGenTask.java:46)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
`
It's a compile time error

**Comment by sav007** [comment]
Yeah seems it an Moshi error, I see PR is open to address this.

**Comment by nicusorflorin** [comment]
if you mean PR #735 , it doesn't, i built the android gradle plugin with what you have in the PR locally and the nesting issue is still there

**Comment by sav007** [comment]
What I meant is this PR: https://github.com/square/moshi/pull/350

**Comment by nicusorflorin** [comment]
@sav007 apparently it was fixed in their latest release, can the updated moshi be added to the next apollo release?

**Comment by digitalbuddha** [comment]
sure! what to open a pr?

**Comment by sav007** [comment]
it was merged couple days ago not sure if a new version available already
