### ISSUE TITLE
ApolloParseException: Failed to parse http response after upgrading to 0.4.3

### ISSUE THREAD

**Issue by akarekal** [apollographql/apollo-android#767]
After upgrading to 0.4.3, this exception is being thrown
``` 
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
```

for the query

```
query X($Y: [String!]!) {
  Z {
    A(Y: $Y) {
      elements {
        ...fragmentA
      }
    }
  }
}

fragment fragmentA on P {
    id
    __typename
    Z {
      __typename
      ...fragmentB
    }
}

fragment fragmentB on C {
   D: F {
      __typename
      M {
        ...fragmentC
      }
      N {
        ...fragmentC
      }
   }
}
fragment fragmentC on L {
  __typename
  contentSummary {
    __typename
    ... on S {
      T {
        Y
      }
    }
    ... on P {
      E {
        R
      }
    }
    ... on Q {
      B {
        D
      }
    }
    ... on R {
      A {
        C
      }
    }
  }
}
```

In the schema `contentSummary` is non-null

In 0.4.2 it was parsing correctly, but in 0.4.3, it throws error 
```
Caused by: java.lang.NullPointerException: contentSummary == null
```
The query is not changed 
Let me know if you need more details

**Comment by sav007** [comment]
Could you please provide the full stack trace for this error?

**Comment by akarekal** [comment]
```
12-20 14:22:38.539 16770 21256 E A: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93)
12-20 14:22:38.539 16770 21256 E A:  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
12-20 14:22:38.539 16770 21256 E A:  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
12-20 14:22:38.539 16770 21256 E A:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-20 14:22:38.539 16770 21256 E A:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-20 14:22:38.539 16770 21256 E A:  at java.lang.Thread.run(Thread.java:761)
12-20 14:22:38.539 16770 21256 E A: Caused by: java.lang.NullPointerException: contentSummary == null
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.api.internal.Utils.checkNotNull(Utils.java:27)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.C.<init>(C.java:124)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.C$Mapper.map(C.java:303)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$D$Fragments$Mapper.map(A.java:452)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$D$Mapper$1.read(A.java:468)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$D$Mapper$1.read(A.java:465)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:226)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$D$Mapper.map(B.java:465)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$E$Mapper$1.read(B.java:290)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$E$Mapper$1.read(B.java:287)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:137)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$E$Mapper.map(B.java:287)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$Mapper$1.read(B.java:129)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$Mapper$1.read(B.java:126)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:137)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.B$Mapper.map(B.java:126)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Y$Fragments$Mapper.map(F.java:353)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Y$Mapper$1.read(F.java:372)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Y$Mapper$1.read(F.java:369)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:226)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Y$Mapper.map(F.java:369)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Mapper$2.read(F.java:179)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Mapper$2.read(F.java:176)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:137)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.F$Mapper.map(F.java:176)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Element$Fragments$Mapper.map(G.java:629)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Element$Mapper$3.read(G.java:661)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Element$Mapper$3.read(G.java:658)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:226)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Element$Mapper.map(G.java:658)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$X$Mapper$1$1.read(G.java:444)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$X$Mapper$1$1.read(G.java:441)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader$ListItemReader.readObject(RealResponseReader.java:311)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$X$Mapper$1.read(G.java:441)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$X$Mapper$1.read(G.java:438)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:164)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$X$Mapper.map(G.java:438)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$FV1Resource$Mapper$1.read(G.java:342)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$FV1Resource$Mapper$1.read(G.java:339)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:137)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$FV1Resource$Mapper.map(G.java:339)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Data$Mapper$1.read(G.java:242)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Data$Mapper$1.read(G.java:239)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:137)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Data$Mapper.map(G.java:239)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.W.G$Data$Mapper.map(G.java:234)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:62)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:57)
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
12-20 14:22:38.539 16770 21256 E A:  ... 8 more
```

**Comment by akarekal** [comment]
@sav007 any update on this issue?
Thanks!

**Comment by sav007** [comment]
Sorry for the delay, looking at the logs seems issue with this field could you check the raw response from the server, if it's not null and the server returns null then it's an issue on the server side.

**Comment by akarekal** [comment]
@sav007 the raw response is not null, and the same response works on 0.4.2, but fails on 0.4.3
The field `contentSummary` is nested, so if outer field is null, then `contentSummary` will be null
But this was correctly parsed in 0.4.2
Thanks

**Comment by sav007** [comment]
Is it possible to get the schema.json file and the raw response, that I can take a look. You can DM me in slack.

**Comment by akarekal** [comment]
@sav007 I saw that the response has `contentSummary` and its type `Object`
In the generated file for the fragment,
```
final ContentSummary contentSummary = reader.readObject($responseFields[10], new ResponseReader.ObjectReader<ContentSummary>() {
        @Override
        public ContentSummary read(ResponseReader reader) {
          return contentSummaryFieldMapper.map(reader);
        }
      });
```
The value `contentSummary` is null after the object is read and hence `Caused by: java.lang.NullPointerException: contentSummary == null` is thrown

Till this line, I see `contentSummary` in the response
<img width="679" alt="screen shot 2018-01-03 at 12 03 22 pm" src="https://user-images.githubusercontent.com/22452118/34537765-76409d12-f07e-11e7-8584-1e66063bb093.png">

**Comment by sav007** [comment]
Sorry for the delay, holidays.

Still confused  `fragmentC` is defined on type `L` if from schema definition of type `L` it defined as non-null then it must be present in the response all the time otherwise it's schema violation.

Could you please be more explicit on `In 0.4.2, if the fragment is not present, it creates new object and returns`?

**Comment by akarekal** [comment]
@sav007 

```
example A:

  contentSummary {
    __typename
    ... on B {
      C {
        D
      }
  }
  ... on F {
      D {
        L
      }
    }

example B:

contentSummary {
    __typename
    ... on B {
      C {
        D
      }
  }
```

in example A, we assume there are 2 fragments B and F for `__typename` 
in example B, we want only fragment B, but the response gives us fragment F also and it tries to parse F, and it fails.

Previously in 0.4.2, if we did not request Fragment F, while parsing it would create a new object if that fragment is not present and in 0.4.3 it returns null

**Comment by sav007** [comment]
wait why for example B it generates fragment F. It's not part of the query. it shouldn't be in the generated model at all. Are these 2 examples are 2 different queries?

**Comment by akarekal** [comment]
@sav007 
It does not generate Fragment F for example B, but if the response contains Fragment F it returns null

In 0.4.2
it generates

```
@Override
      public ContentSummary map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Y Y = reader.readConditional($responseFields[1], new ResponseReader.ConditionalTypeReader<Y>() {
          @Override
          public Y read(String conditionalType,
              ResponseReader reader) {
            return YFieldMapper.map(reader);
          }
        });
        return new ContentSummary(__typename, Y, B, A, Z);
      }
    }
```

But in 0.4.3
it generates
```
@Override
      public ContentSummary map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Y Y = reader.readConditional($responseFields[1], new ResponseReader.ConditionalTypeReader<Y>() {
          @Override
          public Y read(String conditionalType,
              ResponseReader reader) {
            return YFieldMapper.map(reader);
          }
        });
        return null;
      }
    }
```
And hence if the response has a different fragment than the specified in the query , it returns null

**Comment by sav007** [comment]
Oh, that's definitely wrong. Is Y is inline fragment, and could you please try 0.4.4-SNAPSHOT if the issue is still there

**Comment by akarekal** [comment]
@sav007 sure will try 0.4.4-SNAPSHOT, yes Y is inline fragment

**Comment by sav007** [comment]
Are you sure that it's 0.4.3 version as I don't recognize the code generated:
if it's a inline fragment then it should look like this:
https://github.com/apollographql/apollo-android/blob/0.4.3/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestQuery.java#L193
or
https://github.com/apollographql/apollo-android/blob/0.4.3/apollo-compiler/src/test/graphql/com/example/inline_fragments_with_friends/TestQuery.java#L204

**Comment by akarekal** [comment]
@sav007 sorry, yes its like this 
https://github.com/apollographql/apollo-android/blob/0.4.3/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestQuery.java#L193

**Comment by sav007** [comment]
Then I confused about the error. Looking into original stack trace the exception happens in mapping fragment not inline fragment
```
Caused by: java.lang.NullPointerException: contentSummary == null
12-20 14:22:38.539 16770 21256 E A:  at com.apollographql.apollo.api.internal.Utils.checkNotNull(Utils.java:27)
12-20 14:22:38.539 16770 21256 E A:  at org.Z.apollo.fragment.C.<init>(C.java:124)
```
Is there anyway to simplify the original query and reproduce this issue to identify the problem?

**Comment by akarekal** [comment]
@sav007 

Based on this 
https://github.com/apollographql/apollo-android/blob/0.4.3/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestQuery.java#L193

We see that  `Hero` can be of `AsHuman` or `AsDroid`.
If the are mentioned in the query, they get parsed correctly.

If `AsHuman` is not mentioned, and only `AsDroid` is mentioned, then if response contains `AsDroid`, then the `if` conditions will fail and it will return `null`.

If schema has `Hero` as `non-null` then `checkNotNull` will throw null pointer exception.

but previously in 0.4.2, even if `AsDroid` is not mentioned in the query, a new `Hero` object would be returned

**Comment by sav007** [comment]
> If schema has Hero as non-null then checkNotNull will throw null pointer exception.

That is interesting point. Let me try to reproduce it on our test fixtures.

**Comment by akarekal** [comment]
Sure thanks!

**Comment by akarekal** [comment]
@sav007 when is the next release ?

**Comment by sav007** [comment]
I will try to make it this week

**Comment by sp00ne** [comment]
I'm getting the same error, however here I have the following structure

```
<optional> {
 ...inlineFragment
}
```

When the optional = `null`, I get a "Failed to parse http response"
