### ISSUE TITLE
Process 'command '../sdk/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by techartist** [apollographql/apollo-android#779]
I have an issue where apollo is failing to build if I try to change a query.  I know the query is correct, I'm running it in the GraphQL client and it executes properly.  This just happened all of the sudden.  I'm running Kotlin 1.2.10 and apollo version 0.4.1

I'm tearing my hair out here.  Please help.  

Here is the stack trace: 

Error:14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':sdk:generateDevApolloIR'.
14:54:52.543 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/Users/kristywelsh/Dropbox/Workspaces/RangerHealth/ranger_droid/sdk/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1
14:54:52.544 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:54:52.544 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sdk:generateDevApolloIR'.
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
14:54:52.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
14:54:52.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
14:54:52.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
14:54:52.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
14:54:52.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
14:54:52.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:54:52.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
14:54:52.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
14:54:52.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
14:54:52.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
14:54:52.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
14:54:52.550 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
14:54:52.551 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
14:54:52.551 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
14:54:52.551 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
14:54:52.551 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
14:54:52.551 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:54:52.552 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:54:52.552 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:54:52.552 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/kristywelsh/Dropbox/Workspaces/RangerHealth/ranger_droid/sdk/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1
14:54:52.552 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:380)
14:54:52.552 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
14:54:52.553 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:182)
14:54:52.553 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1071)
14:54:52.553 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1066)
14:54:52.553 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.Project$exec$7.call(Unknown Source)
14:54:52.553 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:36)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.NodeExecRunner.doExecute(NodeExecRunner.groovy:44)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:66)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.moowork.gradle.node.task.NodeTask.exec(NodeTask.groovy:81)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.apollographql.apollo.gradle.ApolloIRGenTask.exec(ApolloIRGenTask.java:69)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
14:54:52.554 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
14:54:52.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
14:54:52.556 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
14:54:52.556 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
14:54:52.556 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 27 more
14:54:52.556 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:54:52.556 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:54:52.557 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
14:54:52.557 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
14:54:52.557 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 24s

**Comment by sav007** [comment]
':sdk:generateDevApolloIR' tells that smth wrong with the query, is this log from AS or from command line? If you try to build it from terminal do you see any additional errors?

**Comment by juicycleff** [comment]
```
Gueva\app\build\apollo-codegen\node_modules\apollo-codegen\lib\cli.js generate C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\src\main\graphql\api\AllConversation.graphql -
-add-typename --schema C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\src\main\graphql\api\schema.json --output C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\bui
ld\generated\source\apollo\generatedIR\debug\src\main\graphql\api\DebugAPI.json --operation-ids-path C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\build\generated\source\a
pollo\generatedIR\debug\src\main\graphql\api\DebugOperationIdMap.json --merge-in-fields-from-fragment-spreads false --target json
Successfully started process 'command 'C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\.gradle\nodejs\node-v6.7.0-win-x64\node.exe''
SyntaxError: C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\src\main\graphql\api\schema.json: Unexpected token ∩┐╜ in JSON at position 0
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:573:27)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.loadSchema (C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\build\apollo-codegen\node_modules\apollo-codegen\src\loading.ts:23:22)
    at Object.generate (C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\build\apollo-codegen\node_modules\apollo-codegen\src\generate.ts:29:7)
    at Object.yargs.command.command.command.argv [as handler] (C:\Users\juicycleff\Documents\GuevaINC\Android\Gueva\app\build\apollo-codegen\node_modules\apollo-codegen\src\cli.js:19
1:7)
```

Anyway to fix this my JSON file is ok, I even tested with the schema.json file in the example projects still same error

**Comment by sav007** [comment]
Closing due to inactivity.

**Comment by singhalmanav** [comment]
I'm also getting the same error. I double checked the schema.json and .graphql query file.

Error:org.gradle.process.internal.ExecException: Process 'command
'......app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

I'm using apollo v0.4.4 and kotlin v1.2.20. Can anyone tell me why Apollo is throwing this error during code generation?

**Comment by singhalmanav** [comment]
I'm getting this error with Apollo v0.4.4 but the codegen works fine with v0.4.3.

Error:org.gradle.process.internal.ExecException: Process 'command
'......app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

**Comment by pro100svitlo** [comment]
any updates?

**Comment by antonKozyriatskyi** [comment]
Had this issue because I forgot to add `.graphql` extension to the name of a file with query.

**Comment by vladostaci** [comment]
I got the same error because I didn't include any files with .graphql extension containing the queries/mutations.

**Comment by shivaambi** [comment]
i am also facing the same error please help

**Comment by shivaambi** [comment]
Issue in the schema file which is inside the graphql folder check the schema file must contain the name of query which you are calling.

For example if you have query

query FilmsList{ filmsList{ name } }

then filmsList must be available in your schema.

**Comment by minobilis** [comment]
I got this error message for mutation without name. After adding name to mutation error gone.

**Comment by ghatnandurkar** [comment]
Yes. I gave some name to query and it got resolved.
query ABC(........)

**Comment by AnkitPandey14ap** [comment]
I got the same error cause by mistake i typed a word in schema.json file

**Comment by tejakolla** [comment]
Am getting the same error from morning please help me out with this error.

**Comment by AmirHosein-Farhadi** [comment]
Hello Guys
I was Getting The Same Error Because My `schema.json` file was the problem
i changed it now the problem is gone
wish you luck

**Comment by AmirHosein-Farhadi** [comment]
> Am getting the same error from morning please help me out with this error.

You need to provide` <any>.graphql` file and `schema.json`

1. Check if your query or mutation is available in a `.graphql` file
2. Replace you `schema.json` file (mine was enhanced by apollo in my angular app and was not working properly in android studio)

**Comment by praveen-mobinius** [comment]
Still I'm facing the same issue, I tried all the possibilities mentioned above. But its not working

**Comment by evii** [comment]
I had the same error and after an hour of trying to solve it I realised I didnt put the ".graphql" extension to my query file.

Be sure that in your graphql folder you put: 

 - schema.json  
 - yourQuery.graphql

files.
