### ISSUE TITLE
Apollo compiler failing for valid query

### ISSUE THREAD

**Issue by mwajeeh** [apollographql/apollo-android#800]
Apollo compiler generates code for the following query:
 
```
fragment Setting on Setting {
  __typename
  value {
    __typename
    ... on StringListSettingValue {
      list
    }
  }
}

query queryName($key: String!, $nodeID: String!, $subkey: String) {
  queryName(key: $key, nodeID: $nodeID, subkey: $subkey) {
    ...Setting
  }
}
```
But starts failing for the following valid query:

```
fragment Setting on Setting {
  __typename
  value {
    __typename
    ... on StringListSettingValue {
      list
    }
  }
  ... on SelectSetting {
    options {
      allowFreeText
      id
      label
    }
  }
}

query queryName($key: String!, $nodeID: String!, $subkey: String) {
  queryName(key: $key, nodeID: $nodeID, subkey: $subkey) {
    ...Setting
  }
}

```
with this error:

```
* What went wrong:
Execution failed for task ':domain:generateDebugApolloClasses'.
> non-abstract type AsStringListSettingValue cannot declare abstract method __typename

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':domain:generateDebugApolloClasses'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalArgumentException: non-abstract type AsStringListSettingValue cannot declare abstract method __typename
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.TypeSpec$Builder.build(TypeSpec.java:585)
        at com.apollographql.apollo.compiler.UtilKt.confirmToProtocol(Util.kt:442)
        at com.apollographql.apollo.compiler.SchemaTypeSpecBuilder.interfaceTypeSpec(SchemaTypeSpecBuilder.kt:61)
        at com.apollographql.apollo.compiler.SchemaTypeSpecBuilder.build(SchemaTypeSpecBuilder.kt:27)
        at com.apollographql.apollo.compiler.ir.Field.toTypeSpec(Field.kt:35)
        at com.apollographql.apollo.compiler.SchemaTypeSpecBuilder.nestedTypeSpecs(SchemaTypeSpecBuilder.kt:110)
        at com.apollographql.apollo.compiler.SchemaTypeSpecBuilder.interfaceTypeSpec(SchemaTypeSpecBuilder.kt:34)
        at com.apollographql.apollo.compiler.SchemaTypeSpecBuilder.build(SchemaTypeSpecBuilder.kt:27)
        at com.apollographql.apollo.compiler.ir.Fragment.toTypeSpec(Fragment.kt:32)
        at com.apollographql.apollo.compiler.ir.CodeGenerator$DefaultImpls.toTypeSpec$default(CodeGenerator.kt:6)
        at com.apollographql.apollo.compiler.GraphQLCompiler.writeJavaFiles(GraphQLCompiler.kt:42)
        at com.apollographql.apollo.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:32)
        at com.apollographql.apollo.gradle.ApolloClassGenTask$1.execute(ApolloClassGenTask.java:45)
        at com.apollographql.apollo.gradle.ApolloClassGenTask$1.execute(ApolloClassGenTask.java:39)
        at org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs.doOutOfDate(RebuildIncrementalTaskInputs.java:43)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:40)
        at org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs.outOfDate(RebuildIncrementalTaskInputs.java:27)
        at com.apollographql.apollo.gradle.ApolloClassGenTask.generateClasses(ApolloClassGenTask.java:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 31 more



```

**Comment by mwajeeh** [comment]
So for some reason creating a fragment of `value` made it compile:
```
fragment SettingValue on SettingValue {
  __typename
  ... on StringListSettingValue {
    list
  }
}

fragment Setting on Setting {
  __typename
  ... on SelectSetting {
    options {
      allowFreeText
      id
      label
    }
  }
  value {
    ...SettingValue
  }
}

query queryName($key: String!, $nodeID: String!, $subkey: String) {
  queryName(key: $key, nodeID: $nodeID, subkey: $subkey) {
    ...Setting
  }
}
```

**Comment by sav007** [comment]
I believe if you add `__typename` to
```
... on StringListSettingValue {
      __typename
      list
    }
```
it should work, but yeah this is an issue for sure

**Comment by sav007** [comment]
@mwajeeh could you please check something for me?
Could you please find the `API.json` file in `/build/generated/source/apollo/generatedIR/...` and in this file find failing `Setting` fragment and send me in this ticket or DM in slack?

**Comment by mwajeeh** [comment]
Sent you in slack
