### ISSUE TITLE
ApolloParseException: Failed to parse http response

### ISSUE THREAD

**Issue by KingsMentor** [apollographql/apollo-android#803]
method for apollo client
```
private fun apolloClient(): ApolloClient =
                ApolloClient.builder().serverUrl(BASE_URL)
                        .okHttpClient(OkHttpClient.Builder()
                                .addInterceptor { chain ->
                                    val original = chain.request()
                                    val builder = original.newBuilder().method(original.method(), original.body())
                                    builder.header("Authorization", "Bearer "+AppCache().bearerToken)
                                    chain.proceed(builder.build())
                                }
                                .build())
                        .addCustomTypeAdapter(CustomType.TOKEN, TypeAdapter().customTypeAdapter)
                        .addCustomTypeAdapter(CustomType.ID, TypeAdapter().customTypeAdapter)
                        .build()
```

 on app build.gradle (root)

```
apollo {
    customTypeMapping['Token'] = "java.lang.Object"
    customTypeMapping['ID'] = "java.lang.String"
    nullableValueType = "apolloOptional"
}
```

TypeAdapter Class 

```
public class TypeAdapter {

    public CustomTypeAdapter<Object> customTypeAdapter = new CustomTypeAdapter<Object>() {
        @Override
        public Object decode(String value) {

            return value;

        }

        @Override
        public String encode(Object value) {
            return value.toString();
        }
    };
}


```

I don't know what exactly I am doing wrong, but it always fails with this error

```
io.reactivex.exceptions.OnErrorNotImplementedException: Failed to parse http response
                                                                             at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                             at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                             at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
                                                                             at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                             at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                             at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                             at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                          Caused by: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28)
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93)
                                                                             at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                             at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)
                                                                          Caused by: com.apollographql.apollo.json.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
                                                                             at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.syntaxError(BufferedSourceJsonReader.java:1062)
                                                                             at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.checkLenient(BufferedSourceJsonReader.java:954)
                                                                             at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:379)
                                                                             at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)
                                                                             at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:48)
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28) 
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
                                                                             at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93) 
                                                                             at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
                                                                             at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                             at java.lang.Thread.run(Thread.java:761) 

```
 I am on `version 0.4.3`

**Comment by KingsMentor** [comment]
Adding HttpLoggingInterceptor helped me looking into what the issue really is, which was a malformed json. Here's how you could do that

```
 private val log = HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY);
        private fun apolloClient(): ApolloClient =
                ApolloClient.builder().serverUrl(BASE_URL)
                        .okHttpClient(OkHttpClient.Builder()
                                .addInterceptor(log)
                                .addInterceptor { chain ->
                                    val original = chain.request()
                                    val builder = original.newBuilder().method(original.method(), original.body())
                                    builder.headerå("Authorization", "Bearer "+AppCache().bearerToken +"dshhsv")
                                    chain.proceed(builder.build())
                                }
                                .build())
                        .addCustomTypeAdapter(CustomType.TOKEN, TypeAdapter().customTypeAdapter)
                        .addCustomTypeAdapter(CustomType.ID, TypeAdapter().customTypeAdapter)
                        .build()

```
