### ISSUE TITLE
RecordFieldJsonAdapter.writeJsonValue() add JsonWriter.value(Map)

### ISSUE THREAD

**Issue by stoleruedgar** [apollographql/apollo-android#826]
Apollo version:
apollo-runtime version 0.4.4
apollo-android-support version 0.4.4
apollo-rx2-support 0.4.4

StackTrace:
`  java.lang.RuntimeException: Unsupported record value type: class java.util.LinkedHashMap
                                                           at com.apollographql.apollo.cache.normalized.RecordFieldJsonAdapter.writeJsonValue(RecordFieldJsonAdapter.java:88)
                                                           at com.apollographql.apollo.cache.normalized.RecordFieldJsonAdapter.writeJsonValue(RecordFieldJsonAdapter.java:84)
                                                           at com.apollographql.apollo.cache.normalized.RecordFieldJsonAdapter.toJson(RecordFieldJsonAdapter.java:47)
                                                           at com.ownzones.androidnet.network.cache.SqlNormalizedCache.performMerge(SqlNormalizedCache.java:224)`

We should be able to serialize/deserialize Map to JSON. Either by adding a method to JsonWriter/JsonReader for Map or provide an interface similar to CacheReference.serialize()

**Comment by sav007** [comment]
Sorry for confusion here, but what the issue? Why `map` is been serialized to SQL cache? Is it graphql custom type?

**Comment by sav007** [comment]
Closing due to inactivity
