### ISSUE TITLE
Execution failed for task ':app:generateDebugApolloIR'.

### ISSUE THREAD

**Issue by pro100svitlo** [apollographql/apollo-android#872]
Hi!
I am trying to use schema from androidSample project.
put all files to src/main/graphql/com.test.app/

try to build app, but get next error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugApolloIR'.
> Process 'command '/Users/myUser/Android/ownProjects/testGraph/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1
```

also may be important - I am using Kotlin.
here is my gradle file:
```
//gradle project
buildscript {
    ext.kotlin_version = '1.2.31'
    ext.apolloGraphQL_version = '0.4.4'
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.apollographql.apollo:apollo-gradle-plugin:$apolloGraphQL_version"
        classpath 'io.fabric.tools:gradle:1.25.1'
    }
}

//gradle app module
apply plugin: 'com.android.application'
apply plugin: 'com.apollographql.android'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'io.fabric'
```

I also run it with ```--info ```. here is full log of it
```
Executing tasks: [:app:assembleDebug]

The client will now receive all logging from the daemon (pid: 4654). The daemon log file: /Users/myUser/.gradle/daemon/4.1/daemon-4654.out.log
Starting 15th build in daemon [uptime: 38 mins 34.29 secs, performance: 99%]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 8 worker leases.
Creating new cache for fileHashes, path /Users/myUser/Android/ownProjects/testGraph/.gradle/4.1/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@34836fad
Creating new cache for plugin-use-metadata, path /Users/myUser/.gradle/caches/4.1/plugin-resolution/plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@34313148
Creating new cache for client-status, path /Users/myUser/.gradle/caches/4.1/plugin-resolution/client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@34313148
Starting Build
Settings evaluated using settings file '/Users/myUser/Android/ownProjects/testGraph/settings.gradle'.
Projects loaded. Root project using build file '/Users/myUser/Android/ownProjects/testGraph/build.gradle'.
Included projects: [root project 'testApp', project ':app']
Configuration on demand is an incubating feature.
Evaluating root project 'testApp' using build file '/Users/myUser/Android/ownProjects/testGraph/build.gradle'.
Creating new cache for metadata-1.1/results, path /Users/myUser/.gradle/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@5d6aee84
Creating new cache for metadata-2.23/module-metadata, path /Users/myUser/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@14e2cef6
Creating new cache for metadata-2.23/artifact-at-repository, path /Users/myUser/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@14e2cef6
Evaluating project ':app' using build file '/Users/myUser/Android/ownProjects/testGraph/app/build.gradle'.
Creating configuration androidTestUtil
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration api
Creating configuration implementation
Creating configuration runtimeOnly
Creating configuration compileOnly
Creating configuration wearApp
Creating configuration annotationProcessor
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestApi
Creating configuration androidTestImplementation
Creating configuration androidTestRuntimeOnly
Creating configuration androidTestCompileOnly
Creating configuration androidTestWearApp
Creating configuration androidTestAnnotationProcessor
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testApi
Creating configuration testImplementation
Creating configuration testRuntimeOnly
Creating configuration testCompileOnly
Creating configuration testWearApp
Creating configuration testAnnotationProcessor
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugApi
Creating configuration debugImplementation
Creating configuration debugRuntimeOnly
Creating configuration debugCompileOnly
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration androidTestDebugCompile
Creating configuration androidTestDebugApk
Creating configuration androidTestDebugProvided
Creating configuration androidTestDebugApi
Creating configuration androidTestDebugImplementation
Creating configuration androidTestDebugRuntimeOnly
Creating configuration androidTestDebugCompileOnly
Creating configuration androidTestDebugWearApp
Creating configuration androidTestDebugAnnotationProcessor
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugApi
Creating configuration testDebugImplementation
Creating configuration testDebugRuntimeOnly
Creating configuration testDebugCompileOnly
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseApi
Creating configuration releaseImplementation
Creating configuration releaseRuntimeOnly
Creating configuration releaseCompileOnly
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseApi
Creating configuration testReleaseImplementation
Creating configuration testReleaseRuntimeOnly
Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Parsing the SDK, no caching allowed
Parsing /Users/myUser/Android/SDK/build-tools/21.1.2/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/23.0.1/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/23.0.3/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/25.0.3/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/26.0.0/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/26.0.2/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/27.0.2/package.xml
Parsing /Users/myUser/Android/SDK/build-tools/27.0.3/package.xml
Parsing /Users/myUser/Android/SDK/emulator/package.xml
Parsing /Users/myUser/Android/SDK/extras/android/m2repository/package.xml
Parsing /Users/myUser/Android/SDK/extras/google/m2repository/package.xml
Parsing /Users/myUser/Android/SDK/extras/intel/Hardware_Accelerated_Execution_Manager/package.xml
Parsing /Users/myUser/Android/SDK/patcher/v4/package.xml
Parsing /Users/myUser/Android/SDK/platform-tools/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-22/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-23/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-24/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-25/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-26/package.xml
Parsing /Users/myUser/Android/SDK/platforms/android-27/package.xml
Parsing /Users/myUser/Android/SDK/sources/android-27/package.xml
Parsing /Users/myUser/Android/SDK/system-images/android-19/google_apis/x86/package.xml
Parsing /Users/myUser/Android/SDK/system-images/android-22/google_apis/x86/package.xml
Parsing /Users/myUser/Android/SDK/tools/package.xml
SDK initialized in 67 ms
Using incremental javac compilation for :app debug.
Using incremental javac compilation for :app debugUnitTest.
Using incremental javac compilation for :app release.
Using incremental javac compilation for :app releaseUnitTest.
Using incremental javac compilation for :app debugAndroidTest.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'android.arch.persistence.room:compiler:1.0.0', 'com.github.bumptech.glide:compiler:4.6.1'.
Selected primary task ':app:assembleDebug' from project :app
Creating new cache for annotation-processors, path /Users/myUser/Android/ownProjects/testGraph/.gradle/4.1/fileContent/annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@73ef47c1
All projects evaluated.
Tasks to be executed: [task ':app:preBuild', task ':app:preDebugBuild', task ':app:compileDebugAidl', task ':app:compileDebugRenderscript', task ':app:nodeSetup', task ':app:installApolloCodegen', task ':app:generateDebugApolloIR', task ':app:generateDebugApolloClasses', task ':app:checkDebugManifest', task ':app:generateDebugBuildConfig', task ':app:mergeDebugShaders', task ':app:compileDebugShaders', task ':app:generateDebugAssets', task ':app:mergeDebugAssets', task ':app:processDebugGoogleServices', task ':app:createDebugCompatibleScreenManifests', task ':app:processDebugManifest', task ':app:fabricGenerateResourcesDebug', task ':app:generateDebugResValues', task ':app:generateDebugResources', task ':app:mergeDebugResources', task ':app:splitsDiscoveryTaskDebug', task ':app:processDebugResources', task ':app:kaptGenerateStubsDebugKotlin', task ':app:kaptDebugKotlin', task ':app:compileDebugKotlin', task ':app:prepareLintJar', task ':app:generateDebugSources', task ':app:javaPreCompileDebug', task ':app:compileDebugJavaWithJavac', task ':app:compileDebugNdk', task ':app:compileDebugSources', task ':app:transformClassesWithDexBuilderForDebug', task ':app:transformClassesWithMultidexlistForDebug', task ':app:transformDexArchiveWithDexMergerForDebug', task ':app:mergeDebugJniLibFolders', task ':app:transformNativeLibsWithMergeJniLibsForDebug', task ':app:processDebugJavaRes', task ':app:transformResourcesWithMergeJavaResForDebug', task ':app:validateSigningDebug', task ':app:packageDebug', task ':app:countDebugDexMethods', task ':app:assembleDebug']
Creating new cache for resourceHashesCache, path /Users/myUser/Android/ownProjects/testGraph/.gradle/4.1/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@34836fad
Creating new cache for fileSnapshots, path /Users/myUser/Android/ownProjects/testGraph/.gradle/4.1/taskHistory/fileSnapshots.bin, access org.gradle.cache.internal.DefaultCacheAccess@5eb16832
Creating new cache for taskHistory, path /Users/myUser/Android/ownProjects/testGraph/.gradle/4.1/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@5eb16832
:app:preBuild (Thread[Task worker for ':',5,main]) started.
:app:preBuild
Skipping task ':app:preBuild' as it has no actions.
:app:preBuild UP-TO-DATE
:app:preBuild (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.
:app:preDebugBuild (Thread[Task worker for ':',5,main]) started.
:app:preDebugBuild
Putting task artifact state for task ':app:preDebugBuild' into context took 0.0 secs.
Creating new cache for metadata-2.23/module-artifacts, path /Users/myUser/.gradle/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@14e2cef6
Skipping task ':app:preDebugBuild' as it is up-to-date (took 0.093 secs).
:app:preDebugBuild UP-TO-DATE
:app:preDebugBuild (Thread[Task worker for ':',5,main]) completed. Took 0.093 secs.
:app:compileDebugAidl (Thread[Task worker for ':',5,main]) started.
:app:compileDebugAidl
Putting task artifact state for task ':app:compileDebugAidl' into context took 0.0 secs.
Skipping task ':app:compileDebugAidl' as it is up-to-date (took 0.016 secs).
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugAidl (Thread[Task worker for ':',5,main]) completed. Took 0.016 secs.
:app:compileDebugRenderscript (Thread[Task worker for ':',5,main]) started.
:app:compileDebugRenderscript
Putting task artifact state for task ':app:compileDebugRenderscript' into context took 0.001 secs.
Skipping task ':app:compileDebugRenderscript' as it is up-to-date (took 0.011 secs).
:app:compileDebugRenderscript UP-TO-DATE
:app:compileDebugRenderscript (Thread[Task worker for ':',5,main]) completed. Took 0.012 secs.
:app:nodeSetup (Thread[Task worker for ':',5,main]) started.
:app:nodeSetup
Putting task artifact state for task ':app:nodeSetup' into context took 0.0 secs.
Skipping task ':app:nodeSetup' as it is up-to-date (took 0.053 secs).
:app:nodeSetup UP-TO-DATE
:app:nodeSetup (Thread[Task worker for ':',5,main]) completed. Took 0.054 secs.
:app:installApolloCodegen (Thread[Task worker for ':',5,main]) started.
:app:installApolloCodegen
Putting task artifact state for task ':app:installApolloCodegen' into context took 0.0 secs.
Skipping task ':app:installApolloCodegen' as it is up-to-date (took 0.003 secs).
:app:installApolloCodegen UP-TO-DATE
:app:installApolloCodegen (Thread[Task worker for ':',5,main]) completed. Took 0.003 secs.
:app:generateDebugApolloIR (Thread[Task worker for ':' Thread 7,5,main]) started.
:app:generateDebugApolloIR
Putting task artifact state for task ':app:generateDebugApolloIR' into context took 0.0 secs.
Executing task ':app:generateDebugApolloIR' (up-to-date check took 0.002 secs) due to:
  Task has failed previously.
Starting process 'command '/Users/myUser/Android/ownProjects/testGraph/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''. Working directory: /Users/myUser/Android/ownProjects/testGraph/app Command: /Users/myUser/Android/ownProjects/testGraph/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node /Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/apollo-codegen/lib/cli.js generate /Users/myUser/Android/ownProjects/testGraph/app/src/main/graphql/com/me/testApp/GihuntRepositoryDetailQuery.graphql /Users/myUser/Android/ownProjects/testGraph/app/src/main/graphql/com/me/testApp/GithuntFeedQuery.graphql /Users/myUser/Android/ownProjects/testGraph/app/src/main/graphql/com/me/testApp/RepoCommentAddedSubscription.graphql /Users/myUser/Android/ownProjects/testGraph/app/src/debug/graphql/com/me/testApp/UserQuery.graphql --add-typename --schema /Users/myUser/Android/ownProjects/testGraph/app/src/debug/graphql/com/me/testApp/schema.json --output /Users/myUser/Android/ownProjects/testGraph/app/build/generated/source/apollo/generatedIR/debug/src/debug/graphql/com/me/testApp/DebugAPI.json --operation-ids-path /Users/myUser/Android/ownProjects/testGraph/app/build/generated/source/apollo/generatedIR/debug/src/debug/graphql/com/me/testApp/DebugOperationIdMap.json --merge-in-fields-from-fragment-spreads false --target json
Successfully started process 'command '/Users/myUser/Android/ownProjects/testGraph/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''
TypeError: Cannot read property 'map' of undefined
    at buildObjectDef (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/graphql/utilities/buildClientSchema.js:178:49)
    at buildType (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/graphql/utilities/buildClientSchema.js:140:16)
    at getNamedType (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/graphql/utilities/buildClientSchema.js:104:19)
    at /Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/graphql/utilities/buildClientSchema.js:275:12
    at Array.map (native)
    at Object.buildClientSchema (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/graphql/utilities/buildClientSchema.js:274:41)
    at Object.loadSchema (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/apollo-codegen/src/loading.ts:28:10)
    at Object.generate (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/apollo-codegen/src/generate.ts:29:7)
    at Object.yargs.command.command.command.argv [as handler] (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/apollo-codegen/src/cli.js:191:7)
    at Object.self.runCommand (/Users/myUser/Android/ownProjects/testGraph/app/build/apollo-codegen/node_modules/yargs/lib/command.js:233:22)
:app:generateDebugApolloIR FAILED
:app:generateDebugApolloIR (Thread[Task worker for ':' Thread 7,5,main]) completed. Took 0.617 secs.
```

can u please explain why it happens and how it can be fixed?

**Comment by blackcj** [comment]
I ran into the same issue and resolved this by switching back to version `0.4.3`. Seems to be a bug with `0.4.4`.

**Comment by pro100svitlo** [comment]
I also tried this version, but in my case there was no luck...

**Comment by hshahdoost** [comment]
I ran into the same issue, on version `0.5.0`. Is there any solid solution to this problem?

**Comment by mum6ojum6o** [comment]
0.4.3 worked for me.
