### ISSUE TITLE
Upgrade path with 

### ISSUE THREAD

**Issue by adri** [apollographql/apollo-android#911]
I'd like to refactor a GraphQL API where a interface `Listing` which is implemented by several types (`SoldPublicListing`, `PublicListing`) should be come an object with all types being removed.

Is there a way to do this without breaking deployed app versions? In the generated code I see all types specifically listed.
In **ListingItemFields.java**
```
  public static final List<String> POSSIBLE_TYPES = Collections.unmodifiableList(Arrays.asList( "SoldPublicListing", "PublicListing", "SoldPrivateListing", "PrivateListing"));
```

It is used here:
```java
public static final class Mapper implements FragmentResponseFieldMapper<Fragments> {
        final ListingItemFields.Mapper listingItemFieldsFieldMapper = new ListingItemFields.Mapper();

        @Override
        public @Nonnull Fragments map(ResponseReader reader, @Nonnull String conditionalType) {
          ListingItemFields listingItemFields = null;
          if (ListingItemFields.POSSIBLE_TYPES.contains(conditionalType)) {
            listingItemFields = listingItemFieldsFieldMapper.map(reader);
          }
          return new Fragments(Utils.checkNotNull(listingItemFields, "listingItemFields == null"));
        }
      }
```

When changing the `Listing` interface to an object, I get the following error:
```
Non-fatal Exception: com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
       at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
....
Caused by java.lang.NullPointerException: listingItemFields == null
       at com.apollographql.apollo.api.internal.Utils.checkNotNull(Utils.java:27)
       at com.ticketswap.query.GetListing$Listing$Mapper$7.com.ticketswap.query.GetListing$Listing$Fragments$Mapper.map(GetListing.java:1733)
       at com.ticketswap.query.GetListing$Listing$Mapper$7.read(GetListing.java:799)
       at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:221)
       at com.ticketswap.query.GetListing$Listing$Mapper.map(GetListing.java:799)
       at com.ticketswap.query.GetListing$Data$Mapper$1.read(GetListing.java:353)
       at com.ticketswap.query.GetListing$Data$Mapper$1.read(GetListing.java:350)
       at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:136)
```

**Comment by sav007** [comment]
Such refactoring will definitely break your app, I would recommend a `deprecation process` where you deprecate old types, fields but keep them for a while  and introduce new changes and after you migrate app safely kill deprecated.

**Comment by kassim** [comment]
What's notable is that the apollo-ios implementation didn't suffer the same issue as our Android one when switching between interface and object

I hadn't had time to look at the generated code but it seems as though apollo-ios is somehow less restrictive
